### PR TITLE
Move table units to main header

### PR DESCRIPTION
**Pull request by pllim**
Moved table units to main header. Updated screenshot and doc. This is a follow-up of #370. @ejeschke , what do you think? I think this is a cleaner way to display column units.

Side note: Table sorting in general is still affected by #257 as it uses `TreeView` for display. For example, sorting by flux column does not really sort the flux values properly.

New display (also in doc):
multidim-plugin-table

When table has masked data (this is explained in doc as text):
screenshot

Note: The reason masked data is "--" instead of 999999 is reported at astropy/astropy#5363.

### CODE REVIEW

**Comment by pllim** [comment]
The second commit replaces the "--" data with 999999 to be consistent with how FITS works:
screenshot-1

**Comment by ejeschke** [comment]
@pllim, I think this is cleaner, and less likely to confuse the header with data.

**Comment by ejeschke** [comment]
Do you want to work on this further, or shall I merge?  The table viewer is your initiative, really.

**Comment by pllim** [comment]
You can merge it. Thanks!

**Pull request merged**
