### PR TITLE
Bump Astropy version to 1.x as 0.3 is pretty old

### PR DESCRIPTION
**Pull request by pllim**
Separate PR for this as requested in https://github.com/ejeschke/ginga/pull/484#discussion_r117358189

### CODE REVIEW

**Comment by pllim** [comment]
@ejeschke , how about including this in next release?

**Comment by ejeschke** [comment]
I'd like to hold off on this for the next release, but we will definitely address it right after that in the dev trunk.

**Comment by ejeschke** [comment]
This is a little bit tricky issue for a couple reasons:
1) for those developers just using the ginga viewer widget, `astropy` isn't needed at all, except to any extent that the `astropy-helpers` relies on it. (Although practically speaking, most developers would probably be using it anyway.)
2) for those using the reference viewer, `astropy` is used in various places, but it depends on which plugins or modules are used or desired to use.  Among these we probably need to find the minimum version that supports all the uses in the standard plugins.

**Comment by pllim** [comment]
> find the minimum version

I would say two releases behind the latest is sufficient? 2.0 is coming out (after 1.0, 1.1, 1.2, 1.3), so requiring 1.0 isn't unreasonable. Does Subaru still use Astropy 0.x series?

**Comment by ejeschke** [comment]
> Does Subaru still use Astropy 0.x series?

We are using 1.3 series for the main instances that my group supports.

But I did have the experience of trying to help someone install it on an older platform and they had trouble building recent astropy due to compilation failures.  For this person, they did not need any of the latest features of astropy.  Since Ginga is a pure python program, I was reminded of how just getting the support packages installed could be an impediment.  

Is astropy a requirement for installing something that uses `astropy-helpers`?

**Comment by pllim** [comment]
> Is astropy a requirement for installing something that uses `astropy-helpers`?

Currently, I believe so. For one, the test runner actually lives in `astropy.tests`. There are discussions to move the test runner out into its own separate thing but no one has time to do it.

**Comment by ejeschke** [comment]
Then that makes me wonder what is the minimum version of astropy in order to use astropy-helpers?

**Comment by pllim** [comment]
> what is the minimum version of astropy in order to use astropy-helpers?

@bsipocz , do you know the answer to this?

**Comment by bsipocz** [comment]
Hmm, that's a good question. We're not cross testing the helpers as astropy is in fact not a requirement of the helpers. The testing framework however is imported in from astropy when 1.1+ version is available. If it isn't, the helpers falls back to the previous version it had.
So as a rule of thumb, a given helpers version is tied to the same astropy version (at least to the same branch), but there is no reason that it shouldn't work with older versions, too.

However, cleanups happen, and old workarounds are getting removed from time to time (old python, sphinx versions, etc.)

**Comment by ejeschke** [comment]
I think we will merge this as is, and update the version requirement as needed if we get a confirmed issue reported.

**Pull request merged**
