### PR TITLE
Refactor wcsmod module into individual modules for each wrapper

### PR DESCRIPTION
**Pull request by ejeschke**
- puts each WCS wrapper in a separate module
- for easier administration and editing

### CODE REVIEW

**Comment by pllim** [comment]
I think `__init__.py` needs some extra imports into the `ginga.util.wcsmod` namespace to make it backward-compatible.

**Comment by ejeschke** [comment]
I was wondering about that.  But I didn't find any grepping through the Ginga source code or testing so far.  Are there some STScI plugins that are importing things that are not present in this version?

**Comment by pllim** [comment]
> Are there some STScI plugins that are importing things that are not present in this version?

Not that I can `grep` but STScI is not the only user of Ginga. What about SunPy etc?

**Comment by ejeschke** [comment]
@pllim, from what I can tell, the only "interesting" imports from `wcsmod` were "WCS", "display_types", "coord_types" and "use".  These are all preserved.  The only other thing of interest might be if someone wanted to import one of the WCS wrapper classes directly.  But there is no place in Ginga that does that, and we don't in any of our Subaru plugins.  Sounds like STScI doesn't either.  I don't think that wouldbe likely for any end users either--they would be using the native WCS, not the wrapper.  So I think we are ok here, actually, so long as these four are preserved.

**Comment by pllim** [comment]
I briefly did import one of the wrapper classes directly for #495 but then undid it as part of your reviews. Therefore, I am satisfied by your explanation above.

**Comment by ejeschke** [comment]
Ginga has unit tests for wcsmod, and these pass with the PR.

**Comment by ejeschke** [comment]
One thing I am thinking about (and I guess I will leave it for a future PR) is to refactor `pixtoradec`, `radectopix` and `pixtosystem` to just be wrappers around the vectorized versions that you created.

**Comment by ejeschke** [comment]
Another thing that this PR does is open the door for using different WCS packages with different images.  So for example, you could have a "gwcs" wrapper for some images and "astropy" for some others.  You can imagine other possibilities.  Pretty straightforward with the changes made here.

**Comment by ejeschke** [comment]
Merging.

**Comment by ejeschke** [comment]
Oh, you might need to remove `wcsmod.pyc` or other cached versions in order to avoid accidentally importing the old module.

**Comment by pllim** [comment]
Yes, this would be useful for #327 and #434.

**Pull request merged**
