### PR TITLE
MultiDim should stack vertically

### LINKED ISSUE #849: MultiDim layout is wrong
multidim_horizontal

The second box should have been stacked horizontally below the first box.

### PR DESCRIPTION
**Pull request by pllim**
Fix #849

### CODE REVIEW

**Comment by ejeschke** [comment]
@pllim, I feel like this should be rather addressed as a plugin setting (preference).  Some keyword where default is like `orientation='vertical'`.  Then code in `build_gui` looks something like:
```
orientation = self.settings.get('orientation', 'vertical')
if orientation is None:
    # orientation should follow window shape
    vbox, sw, orientation = Widgets.get_oriented_box(container, scrolled=True)
else:
    vbox = Widgets.Box(orientation=orientation)
    sw = Widgets.ScrollArea()
    sw.set_widget(vbox)
self.orientation = orientation
...
```

**Comment by ejeschke** [comment]
You will find that there are a number of plugins that auto-orient like this.  Another possibility is to just change the `get_oriented_box()` to need a "more" horizontal shape before returning a horizontally-oriented box.  This is fairly easy to do by altering the check of the aspect ratio in that method.

**Comment by pllim** [comment]
While I like the preferences, I feel like it is not the right hammer for this nail. I have made the aspect ratio check more forgiving for `MultiDim`. Is this okay?

**Comment by pllim** [comment]
Superseded by #851

**Pull request closed without merging**
