### PR TITLE
Consolidate pip dependencies between doc and setup

### LINKED ISSUE #663: Feature Request: Add requirements files
It would be nice to have requirements files, so user can simply do, say, `pip install -r requirements_qt5.txt`, if they want all dependencies for Ginga to run under Qt5.

This thought came to mind when I re-install Anaconda and I run into this or that not found when trying to use a Ginga widget for Jupyter notebook. I had to go back and reinstall missing dependency multiple times until things started working.

### PR DESCRIPTION
**Pull request by pllim**
Fix #663.

This supersedes #709.

@astrofrog , can you please have a look to see if I wrote the setuptools syntax correctly? Thanks! 🙏 

So, I think, with this change
```
python setup.py install
```
becomes
```
pip install .[recommended,qt5]
```
with the latter also `pip install` the specified dependencies.

If you are used to `python setup.py develop`, then it becomes
```
pip install -e .[...]
```

### CODE REVIEW

**Comment by astrofrog** [comment]
This looks good to me!

**Comment by ejeschke** [comment]
Sorry, @pllim, can you rebase?  It's just `WhatsNew` document.

**Comment by pllim** [comment]
@ejeschke , rebased and squashed!

**Comment by ejeschke** [comment]
Tnx, just want to give it a quick test with the new installation method.

**Comment by pllim** [comment]
Huh, weird. The conflict is back. But shouldn't affect your testing.

**Comment by pllim** [comment]
Rebased again.

**Comment by ejeschke** [comment]
`pip install .` seems to work as well.

**Comment by ejeschke** [comment]
It seems that `python setup.py install` still works.  Is that expected?  That's great, if so, for those that are just catching on to the new install scheme.

**Comment by pllim** [comment]
setup.py install still works. @astrofrog, is astropy dev affected pip 19 bug?

**Comment by pllim** [comment]
Tests passed now. They were indeed spurious. FFTM.

**Comment by pllim** [comment]
Note to self: I'll have to look into repo RTD setting to see how to use these new setup.

**Pull request merged**
