### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by pllim**
Address failures reported by @mitya57 in #614.

### CODE REVIEW

**Comment by mitya57** [comment]
:+1: Thanks!

**Comment by ejeschke** [comment]
Thank you, @pllim!  This looks fine to me.

Before I merge, let's discuss the strategy with @olebole and @mitya57 for where this fix should end up.  This is a PR against master.  We could merge this and try to "backport" it  into v2.6.6  (this will require downgrading the version number in `setup.cfg` and then some tag resetting git-fu).  However, I'd like to do one more release before the end of the year (it will be 2.7.0 and include #613 and the long delayed #449). We could also just wait until that release to make the debian release.  Thoughts?

**Comment by olebole** [comment]
I have no problem to wait. When I find some time, I will just take over the [changes](https://launchpadlibrarian.net/346352064/ginga_2.6.5-2_2.6.6-1ubuntu2.diff.gz) made by Dmitry Shachnev from Ubuntu for the mean time.

**Comment by ejeschke** [comment]
> I have no problem to wait. When I find some time, I will just take over the changes made by Dmitry Shachnev from Ubuntu for the mean time.

Excellent.  I'm going to go ahead and merge.

**Comment by mitya57** [comment]
Dmitry Shachnev is me :)

My patches just disabled the wrong tests rather than fixing them. I think it would be better to use a patch based on this PR. If you upload this to Debian, I will sync it back to Ubuntu.

**Comment by olebole** [comment]
@mitya57 Just uploaded 2.6.6-2. BTW, since you are DD: if it fits into your Ubuntu workflow, you are welcome to commit your changes for my packages to the alioth git repo additionally (or instead of) Ubuntu. They are all (debian-astro) team maintained.

**Comment by mitya57** [comment]
@olebole Thanks. I am not particularly interested in this package, but in Ubuntu autopkgtest failures are significant and it blocked migration of my package (pyqt5).

**Comment by pllim** [comment]
I am not familiar on how to patch Debian or Ubuntu, but I'll be happy to submit PRs to your repositories with this fix if you provide instructions. FYI.

**Comment by olebole** [comment]
@pllim Just for patches the easiest is probably to just ping me in the relevant PR. We keep the changes from the released upstream version separately (in [`debian/patches/`](https://anonscm.debian.org/cgit/debian-astro/packages/ginga.git/tree/debian/patches)), and I am not sure whether it is worth to dig into this.
However, if you want, you should read a Debian packaging tutorial first (f.e.  [this one for affiliated packages](https://wiki.debian.org/DebianAstro/AstropyPackagingTutorial/Preparation)), create an account on [alioth](https://alioth.debian.org) and apply for group membership in the [debian-astro team](https://alioth.debian.org/projects/debian-astro/).

**Comment by pllim** [comment]
> I am not sure whether it is worth to dig into this.

Thanks for the info but it does seem pretty involved, so I am not sure either. This is a relevant PR right here but you mentioned above that you can wait, so this is probably a non-issue now?

**Comment by olebole** [comment]
Since it only concerned a test, I thought of just disabling the test in Debian until a new version is out, but @mitya57 proposed to better apply this PR, which I [finally did](https://anonscm.debian.org/cgit/debian-astro/packages/ginga.git/tree/debian/patches/Fix-colormap-test-failures-when-matplotlib-is-installed.patch) in the Debian release 2.6.6-2 of ginga. So, it is a non-issue now.

**Comment by pllim** [comment]
Thank you!

**Pull request merged**
