### PR TITLE
ViewerImageProxy: allow data operations on plotted mosaics

### PR DESCRIPTION
**Pull request by ejeschke**
Adds a `ViewerImageProxy` class, which is a kind of stand-in for an image (i.e. `BaseImage`-based) wrapper.  It looks at images plotted on the canvas and provides SOME methods to treat it as though it was one large single image.  This allows us to save large amounts of memory for mosaiced fields,
because we don't need to allocate one huge ndarray to hold everything, but only plot each image at the proper location and orientation on the viewer's canvas--like a sparse data array.

Several plugins are modified so that they will work with this kind of mosaiced display, particularly `Pick`, `Cuts`, `Histogram`, `PixTable`, `Pan`.

### CODE REVIEW

**Comment by ejeschke** [comment]
@pllim, this is preliminary WIP, but far enough along now for testing and some feedback. Hold the code review for now, as there is much to do there, but try out the `Mosaic` plugin with some tiles (HST?) when you have a chance.  When you have a mosaic up, try using Pick/Cuts/Histogram/PixTable.

In a nutshell, what this does is replace the idea of building one large image with all the tiles in it, and instead just plots them on the ginga canvas relative to the WCS. Advantages are that saves memory, can be faster to create the mosaic and doesn't require the user to specify a FOV size.  Indeed, the tiles can be quite far apart, as they are simply not plotted unless in the clip area.

The downside: most Ginga plugins have been written with the idea that there is a single image "loaded" into the viewer.  Many of them work by trying to get that single image and do something with it.  This PR makes a kind of "proxy" that supports *some* of the image functions; in particular, the functions meant for grabbing small subsets of data and doing some analysis on that.  This PR has been written to allow them to make only minor modifications to work with both "regular" images and the mosaics.

**Comment by pllim** [comment]
Needs a rebase to resolve the conflict.

**Comment by pllim** [comment]
I am thinking to hold off on playing around with this until after #815 is merged and this is rebased on top of that one.

**Comment by ejeschke** [comment]
I think we are running into some TravisCI issues that need to be addressed. Take a look at the build failure and let me know what you think, @pllim.  (Looks like it is still trying to use `astropy-helpers`...)

**Comment by ejeschke** [comment]
> Looks like it is still trying to use astropy-helpers...

My mistake, Looks like ``astropy/ci-helpers`. Now it looks like a version conflict issue between two support packages for the astropy ecosystem.

**Comment by pllim** [comment]
I simply restarted the job and the error went away. 🤷‍♀ 

Please ping me again when this has been rebased on top of #815. Thank you!

**Comment by ejeschke** [comment]
Rebased.

**Comment by ejeschke** [comment]
> Please ping me again when this has been rebased on top of #815.

*Ping!* :smiley_cat:

**Comment by pllim** [comment]
Can you please rebase again to pick up the recent infrastructure updates? Thanks! :sweat_smile:

**Comment by ejeschke** [comment]
Rebased.

**Comment by pllim** [comment]
1. The non-backward compatibility of `Mosaic` broke my [MosaicAuto](https://stginga.readthedocs.io/en/latest/stginga/plugins_manual/mosaicauto.html) plugin downstream.

```
2020-01-23 13:54:28,438 | E | Control.py:445 (error_wrap) | TypeError
mosaic() got an unexpected keyword argument 'new_mosaic'  File ".../ginga/rv/Control.py", line 435, in error_wrap
    return method(*args, **kwargs)
```

I guess I'll have to go into https://github.com/spacetelescope/stginga/blob/master/stginga/plugins/MosaicAuto.py and make it check for Ginga version and apply the correct API, but since you said this is WIP and not ready for code review, I'll hold off on that.

2. When I start `ginga` with some pre-existing config files in my `~/.ginga`, I get the following error but I don't know where it is coming from. However, it only appeared the first two times I ran `ginga` and then mysteriously disappeared!

```
2020-01-23 14:00:53,728 | E | Callback.py:172 (_do_callbacks) | Error making callback 'field-info': 'NoneType' object has no attribute 'extdata'
2020-01-23 14:00:53,728 | E | Callback.py:173 (_do_callbacks) | Traceback:
  File ".../ginga/misc/Callback.py", line 156, in _do_callbacks
    res = method(*cb_args, **cb_kwargs)

  File ".../ginga/rv/plugins/Info.py", line 492, in field_info
    if '_info_info' not in channel.extdata:

2020-01-23 14:00:53,728 | E | Callback.py:172 (_do_callbacks) | Error making callback 'field-info': 'NoneType' object has no attribute 'fitsimage'
2020-01-23 14:00:53,728 | E | Callback.py:173 (_do_callbacks) | Traceback:
  File ".../ginga/misc/Callback.py", line 156, in _do_callbacks
    res = method(*cb_args, **cb_kwargs)

  File ".../ginga/rv/plugins/Cursor.py", line 158, in field_info_cb
    fitsimage = channel.fitsimage
```

3. The `Mosaic` plugin from this PR seems to work, but I don't see the mosaic's output buffer in `Contents`. As a result, there is no way I can write it out via `SaveImage`, which reads from `Contents`.

**Comment by pllim** [comment]
To clarify, for the `Mosaic`, I used simulated JWST NIRCam data rather than HST data. They are the three `*nrca5_assign_wcs.fits` files in [Ginga dev Box folder](https://stsci.app.box.com/folder/3381606676). I am also using Numpy 1.18.1 from `conda-forge` and dev version of `astropy`.

4. `Pick` failed to find the peak in the resulting mosaic, although as far as my eyes can see, I think the source is pretty decent?

Screenshot from 2020-01-23 14-12-55

```
2020-01-23 14:11:12,583 | W | AutoCuts.py:173 (calc_histogram) | NaN's found in data, using workaround for histogram
2020-01-23 14:11:12,584 | E | Callback.py:172 (_do_callbacks) | Error making callback 'set': autodetected range of [nan, nan] is not finite
2020-01-23 14:11:12,584 | E | Callback.py:173 (_do_callbacks) | Traceback:
  File "...ginga/misc/Callback.py", line 156, in _do_callbacks
    res = method(*cb_args, **cb_kwargs)

  File ".../ginga/ImageView.py", line 2719, in auto_levels_cb
    self.auto_levels()

  File ".../ginga/ImageView.py", line 2692, in auto_levels
    loval, hival = autocuts.calc_cut_levels(image)

  File ".../ginga/AutoCuts.py", line 153, in calc_cut_levels
    bnch = self.calc_histogram(data, pct=self.pct, numbins=self.numbins)

  File ".../ginga/AutoCuts.py", line 187, in calc_histogram
    density=False)

  File "<__array_function__ internals>", line 6, in histogram

  File ".../numpy/lib/histograms.py", line 795, in histogram
    bin_edges, uniform_bins = _get_bin_edges(a, bins, range, weights)

  File ".../numpy/lib/histograms.py", line 429, in _get_bin_edges
    first_edge, last_edge = _get_outer_edges(a, range)

  File ".../numpy/lib/histograms.py", line 327, in _get_outer_edges
    "autodetected range of [{}, {}] is not finite".format(first_edge, last_edge))

2020-01-23 14:11:12,645 | E | Pick.py:1575 (update_pick) | Error calculating quality metrics: Cannot find bright peaks
2020-01-23 14:11:12,646 | E | Pick.py:1582 (update_pick) |   File ".../ginga/rv/plugins/Pick.py", line 1499, in update_pick
    raise Exception(msg)
```

**Comment by pllim** [comment]
5. For the `Cuts` plugin, I drew a line across the mosaic buffer but the plot remains empty. Nothing is plotted and I don't see any errors on the terminal.

6. Similarly, I also get empty plot for `Histogram` but there are errors:

```
2020-01-23 14:19:36,697 | W | AutoCuts.py:173 (calc_histogram) | NaN's found in data, using workaround for histogram
2020-01-23 14:19:36,697 | W | logger.py:174 (_showwarning) | .../ginga/AutoCuts.py:177: RuntimeWarning: All-NaN slice encountered
  minval = np.nanmin(data)

2020-01-23 14:19:36,697 | W | logger.py:174 (_showwarning) | .../ginga/AutoCuts.py:178: RuntimeWarning: All-NaN slice encountered
  maxval = np.nanmax(data)

Error making callback 'draw-event': autodetected range of [nan, nan] is not finite
Traceback:
  File ".../ginga/misc/Callback.py", line 156, in _do_callbacks
    res = method(*cb_args, **cb_kwargs)

  File ".../ginga/rv/plugins/Histogram.py", line 509, in draw_cb
    return self.redo()

  File ".../ginga/rv/plugins/Histogram.py", line 342, in redo
    res = self.histogram_data(data_np, pct=1.0, numbins=numbins)

  File ".../ginga/rv/plugins/Histogram.py", line 321, in histogram_data
    return self.autocuts.calc_histogram(data, pct=pct, numbins=numbins)

  File ".../ginga/AutoCuts.py", line 187, in calc_histogram
    density=False)

  File "<__array_function__ internals>", line 6, in histogram

  File ".../numpy/lib/histograms.py", line 795, in histogram
    bin_edges, uniform_bins = _get_bin_edges(a, bins, range, weights)

  File ".../numpy/lib/histograms.py", line 429, in _get_bin_edges
    first_edge, last_edge = _get_outer_edges(a, range)

  File ".../numpy/lib/histograms.py", line 327, in _get_outer_edges
    "autodetected range of [{}, {}] is not finite".format(first_edge, last_edge))
```

7. `PixTable` shows all `nan` even when the "Value" in info bar shows actual numbers.

**Comment by ejeschke** [comment]
@pllim, thanks for testing!  I'll get to points 1, 2, and 3, but for now could you update the PR checkout and try again 4, 5, 6, & 7?  Seems I messed up this PR when I merged #815, and I just submitted a PR that should make it right.

**Comment by ejeschke** [comment]
> When I start ginga with some pre-existing config files in my ~/.ginga, I get the following error but I don't know where it is coming from. However, it only appeared the first two times I ran ginga and then mysteriously disappeared!

Has it returned? Does it happen every time you start up ginga from terminal?

**Comment by ejeschke** [comment]
> The Mosaic plugin from this PR seems to work, but I don't see the mosaic's output buffer in Contents. 

We could create `Contents` and `Thumbs` entries that would rebuild the mosaic when clicked.

> As a result, there is no way I can write it out via SaveImage, which reads from Contents.

This is kind of a limitation of this approach--because no single image is "built", there is no one large image that can be written out as a FITS file.

**Comment by ejeschke** [comment]
>  am also concerned about taking away the ability to save the output mosaic. Is there a way to retain the "classic" mosaic plugin so I can still save the mosaic out somehow?

I'm certainly not opposed to keeping the existing plugin around--we still have uses for that here at Subaru.  I think we'd just need to be careful in naming and documentation, so that new users don't get confused between the two plugins.

**Comment by ejeschke** [comment]
Existing vs. New plugin

New plugin
---------------
- no need to allocate a large array to hold all the image contents (saving time and potentially a very large amount of memory if there are a lot of images in the mosaic)
- no need to specify output FOV or worry about it
- little bit quicker to build mosaics (depends again on constituent images)
- Complicates operations on "the image" (because there is no one image)
- Makes it difficult to save the mosaic as a file

Existing plugin
--------------------
- Works with existing single image workflows/plugins, because it builds a single image from the constituents
- Can use lots of memory, depending on size
- Can be slower, depending on size
- Must specify FOV for best results
- Has the problem of making up a value for the space between images (which affects numerical operations on the array--should it be `NaN`, `0`, etc)

**Comment by ejeschke** [comment]
@pllim, let me know what you think of this change: I've restored the old `Mosaic` plugin, and renamed this one "Collage". It's kind of descriptive of how it works.

**Comment by ejeschke** [comment]
Doing a comparison.  It's interesting that `Mosaic` creates the following mosaic:
Screenshot from 2020-01-23 19-00-14

while `Collage` creates this one (stacking depends on the order that you drag them in):
Screenshot from 2020-01-23 19-07-04

Here's ds9: 
Screenshot from 2020-01-23 19-01-17

Looks like `Mosaic` might have a bug we need to fix.

**Comment by ejeschke** [comment]
@pllim, any idea about the readthedocs failure?

**Comment by pllim** [comment]
Re: RTD failure -- I think a restart of the job might fix things but currently the only way I know how to restart it in a PR is to push another commit.

**Comment by ejeschke** [comment]
No worries--there will be more commits!

**Comment by pllim** [comment]
Re: RTD failure -- I saw the same error in my project (not PR) and it is due to old cache of older `pip` messing with `pip` v20. I had to manually clear the cache in RTD admin panel and rebuild it before it would pass. I have no idea how to do that for a PR as it doesn't seem to be possible. 🤷‍♀

**Comment by pllim** [comment]
Re: Mosaic bug -- Just to make sure it is a bug in JWST header, I requested dithered HST images. Will update you when I get them.

**Comment by pllim** [comment]
Re: Has it returned? (https://github.com/ejeschke/ginga/pull/812#issuecomment-577965373) -- Yes. For exactly two times, then disappeared.

```
$ ginga --loglevel=30 --stderr
2020-01-29 12:48:20,652 | E | Callback.py:172 (_do_callbacks) | Error making callback 'field-info': 'NoneType' object has no attribute 'extdata'
2020-01-29 12:48:20,652 | E | Callback.py:173 (_do_callbacks) | Traceback:
  File ".../ginga/misc/Callback.py", line 156, in _do_callbacks
    res = method(*cb_args, **cb_kwargs)

  File ".../ginga/rv/plugins/Info.py", line 492, in field_info
    if '_info_info' not in channel.extdata:

2020-01-29 12:48:20,652 | E | Callback.py:172 (_do_callbacks) | Error making callback 'field-info': 'NoneType' object has no attribute 'fitsimage'
2020-01-29 12:48:20,652 | E | Callback.py:173 (_do_callbacks) | Traceback:
  File ".../ginga/misc/Callback.py", line 156, in _do_callbacks
    res = method(*cb_args, **cb_kwargs)

  File ".../ginga/rv/plugins/Cursor.py", line 158, in field_info_cb
    fitsimage = channel.fitsimage
```

**Comment by pllim** [comment]
In re-trying the plugins, as you requested, here is an updated result:

4. `Pick` works now but emits the following warning, which I am not sure if I should ignore or not. I am using Numpy 1.18.1 from PyPI.

```
2020-01-29 15:47:34,397 | W | logger.py:174 (_showwarning) | .../numpy/core/fromnumeric.py:746: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
```

5. `Cuts` work.

6. `Histogram` work.

7. `PixTable` is not reporting `nan` now but still not reporting the correct number. I see the "Value" showing over 80k over a saturate star on HST image but `PixTable` said like 30 or some really off number over that pixel.

**Comment by pllim** [comment]
I like the idea of `Collage` being a different plugin. I also agree with you that `Mosaic` and `Collage` should be clearly explained in user documentation. The pros and cons you listed in https://github.com/ejeschke/ginga/pull/812#issuecomment-577972226 is very useful info to have in that doc.

I added three dithered exposures of 47 Tuc taken with HST/ACS in https://stsci.app.box.com/folder/101803258253 for you to test things with.

Here is the `Mosaic` of them:

ginga_mosaic

Here is the `Collage` of them:

ginga_collage

They don't show the discrepancy that you are seeing with JWST simulated images [above](https://github.com/ejeschke/ginga/pull/812#issuecomment-577993482), which means that the "bug" is in how Ginga handles WCS differently for the JWST cases between `Mosaic` and `Collage`. It seems that the FITS header of JWST image has PC matrix (unlike the HST image). To add to the complication, the "real" WCS is actually the GWCS in its ASDF extension. So, are you using the FITS WCS or GWCS? If the former, how are the resultant WCS different compared to DS9? I cannot see the WCS of `Collage` output in `Header` like I can for the `Mosaic` output, so I don't know how to find this answer.

**Comment by pllim** [comment]
Maybe related to the discrepancy between `Mosaic` and `Collage` you see in JWST data? spacetelescope/mirage#345

**Comment by ejeschke** [comment]
> It seems that the FITS header of JWST image has PC matrix (unlike the HST image).

Hmm, shouldn't matter, but I should take a look at the code.

> To add to the complication, the "real" WCS is actually the GWCS in its ASDF extension.

Ah, well, Ginga is just using whatever astropy gives us as a wcs.  It would be interesting to check whether we are getting the GWCS embedded in ASDF embedded in FITS thing working correctly.

**Comment by ejeschke** [comment]
> Maybe related to the discrepancy between `Mosaic` and `Collage` you see in JWST data? [spacetelescope/mirage#345](https://github.com/spacetelescope/mirage/pull/345)

That could well be the culprit, if the data you were using has the wrong sign on the PC matrix.  Any way to check?

**Comment by pllim** [comment]
@ejeschke, whether JWST PC matrix is right or wrong, it is still concerning that Mosaic and Collage give different results. They should be consistent, no?

@bhilbert4, what is the status of possibly flipped sign in PC matrix generated by Mirage? Has that mystery been resolved? Please advise. Thank you.

**Comment by bhilbert4** [comment]
We haven't had time to look into that deeply, other than to say that Mirage uses the same thing that the jwst calibration pipeline uses.

**Comment by pllim** [comment]
@ejeschke , looking at your implementation of `ginga.util.mosaic.CanvasMosaicer`, it seems like it uses FITS WCS. For this purpose, I think that is fine (or can be left as a future PR if GWCS is really necessary). However, still would be nice to have `Mosaic` and `Collage` produce consistent results.

**Comment by ejeschke** [comment]
> whether JWST PC matrix is right or wrong, it is still concerning that Mosaic and Collage give different results. They should be consistent, no?

Yes, I agree.  And that should be debugged first.

> looking at your implementation of ginga.util.mosaic.CanvasMosaicer, it seems like it uses FITS WCS. For this purpose, I think that is fine (or can be left as a future PR if GWCS is really necessary).

Unfortunately, it is simply looking at the FITS header. I think it would be better to query the WCS directly to get the rotation and scale.  That should support GWCS.  I think a new PR would be appropriate, basically moving the functions from `ginga.util.wcs` to the wrappers in `ginga.util.wcsmod`. There it could eventually be refactored to make the appropriate calls to the actual wcs objects.

**Comment by ejeschke** [comment]
@pllim, I found a possible bug in the routine that is used by both `Collage` and `Mosaic` when using a PC-matrix based image, but fixing it doesn't seem to change the outcome of the difference in mosaicing shown above.  I'm continuing to look into it.

**Comment by ejeschke** [comment]
Rebased.

**Comment by ejeschke** [comment]
> Yes, I agree. And that should be debugged first.

So, I'm not entirely positive yet, but it seems that the difference can be seen from the compasses shown in the images above.  If you use the orient feature of Ginga (the "o" and "O" keybindings) you can see that the images are the same WRT compass direction, but not WRT to pixels in X. So this likely results from the fact that `Mosaic` builds in an empty image--and I'm guessing that the orientation of the pixel scale for X is reversed from the original image.  Looking at that now.

**Comment by ejeschke** [comment]
@pllim, can you check with master? I pushed up a fix that works for the images I tried.  It was indeed a bug in the creation of the `Mosaic` WCS, in the case of images that only have a PC matrix.  `Mosaic` now works as we expect for JWST images.

**Comment by ejeschke** [comment]
Will update this PR soon.

**Comment by ejeschke** [comment]
Rebased.

**Comment by ejeschke** [comment]
@pllim, I think this one is ready to merge. `Mosaic` was kept as is and no change to interface or operations of regular plugins. `Pick`, `Cuts`, `Histogram`, `PixTable` and `Pan` were modified to work with plotted mosaics (`Collage`).

**Comment by ejeschke** [comment]
Gonna push one more commit with some documentation for `Collage`.

**Comment by pllim** [comment]
Thanks! I'll re-review when I get a chance.

**Comment by ejeschke** [comment]
Rebased.

**Comment by ejeschke** [comment]
> #812 (comment) is still an issue but not a blocker (maybe open a follow up issue for it after merge).

Pushed a fix for this.

> PixTable still reports the wrong value that does not match what is given on Value.

Can you show an example with FITS for this? I worked really hard to squash that one and was pretty sure I had figured it out.  Did it happen when opening a file in the usual way or when using `Collage`?

**Comment by ejeschke** [comment]
> I don't see the Travis CI result of this PR. Did it not run or did it simply not reporting back? Can check again when new commits are pushed.

Not sure what happened, but it looks like it ran when I pushed this last fix.  Seems ok.

**Comment by pllim** [comment]
> Can you show an example with FITS for this?

Any FITS file will do. I used an example HST/ACS image (name goes like `j....fits`) and those 2 JWST simulated images above used to create a `Collage`. Yes, `PixTable` shows the wrong values for both FITS image loaded directly with `Open Files` plugin and also wrong for the buffer in `Collage`. The highlighted number in the middle of `PixValue` table does not match the number reported by `Value` when I mouse around the images.

> looks like it ran

I only see ReadTheDocs reporting back. That one only builds the documentation for this PR. I do not see any result from TravisCI. Seems like the CI ran but not reporting back -- https://travis-ci.org/github/ejeschke/ginga/pull_requests

**Comment by ejeschke** [comment]
> Collage and Mosaic do not play well together. That is, when I have a buffer from Mosaic already and then I use Mosaic, the buffer from Mosaic gets messed up. Maybe this should be a warning on the docs of the plugins.

I assume you mean "buffer from Mosaic and then use *Collage*"?

Unless you press "New Collage" after starting the `Collage` plugin it will use the loaded image (if any) as the reference for positioning any tiles dragged in afterward.  Try making a small mosaic with `Mosaic` then start Collage and drag in another tile.  It should be overplotted in the correct position relative to the others.  Here is an example:

collage_after_mosaic

Using `Mosaic` *after* `Collage` does not really make any sense, since `Mosaic` wants to start by building and loading an empty image with the first thing you drag in. That will displace the tile used by `Collage`, and erase its other plotted tiles.

I agree that these two plugins really don't play well together and the user should choose one or the other and not mix them.  I can add some more documentation on `Collage`'s limitations.  Collages for now should be considered kind of ephemeral, since they never exist as whole images in the sense that other images in Ginga do.  Maybe another PR can be made that will make entries in the channel for them and make it possible to reconstruct them just by clicking on a thumbnail.

**Comment by ejeschke** [comment]
> I only see ReadTheDocs reporting back. That one only builds the documentation for this PR. I do not see any result from TravisCI. Seems like the CI ran but not reporting back 

Isn't [this it](https://travis-ci.org/github/ejeschke/ginga/builds/678835772)?

**Comment by pllim** [comment]
Yes, it ran. But I don't see it here.

Untitled

**Comment by ejeschke** [comment]
> Any FITS file will do. I used an example HST/ACS image (name goes like j....fits) and those 2 JWST simulated images above used to create a Collage. Yes, PixTable shows the wrong values for both FITS image loaded directly with Open Files plugin and also wrong for the buffer in Collage. The highlighted number in the middle of PixValue table does not match the number reported by Value when I mouse around the images.

I just tried several j...fits images in my testdata directory and they are all working fine (image reported in Value matches highlighted value in `PixTable`).  Is the top commit of your PR 27169ce160811a3e2f4587d9de511ec7f4b82958 ?  Could you drop one of the problem images into the shared Box directory?  I'm puzzled by this, because I was having that exact problem, but solved it in commit 06ad68628fe696055aa02bc763b470a744b51001.

**Comment by ejeschke** [comment]
> Yes, it ran. But I don't see it here.

I see what you mean now.  Wonder what the heck is going on with that.  I'll try rebasing another one of the PRs and see if the same thing happens.

**Comment by ejeschke** [comment]
I just rebased the `reproject-plugin` PR #813.  It looks like it is only running the readthedocs build check.  I'll check on the settings in github, but I don't think that problem is related to this PR.  Somehow the regular Travis CI build is not connecting to github any more.

**Comment by pllim** [comment]
Maybe your Travis CI was still using GitHub Services? https://developer.github.com/v3/guides/replacing-github-services/

**Comment by ejeschke** [comment]
I suppose so.  I don't remember touching that for a long time.

**Comment by pllim** [comment]
Image link: https://stsci.box.com/s/3k009ufudki2c5lcug1qjwnscbpqw2wm

What I see (`PixTable` says 86.28 but `Value` says 8352.729). The cursor was not captured but it was centered at the given X and Y in the screenshot right in the middle of the bright thingy.

pixtable_wrong_value

I am using Ginga via SSH, so I am not physically in front of the machine where it is running. Does this matter though?

**Comment by pllim** [comment]
p.s. Yes, I picked up the latest changes from this PR. The `field-info` error is gone. Thanks!

**Comment by ejeschke** [comment]
Apparently, ginga should have been [auto-migrated on February 1, 2019]( https://blog.travis-ci.com/2019-01-31-github-services-integration-deprecation ).  I guess that didn't work...

**Comment by ejeschke** [comment]
> The field-info error is gone.

Not sure why you were getting a `None` channel in that callback.  I couldn't reproduce it.  But good to have checks in the callbacks anyway...

**Comment by ejeschke** [comment]
Screenshot from 2020-04-23 15-52-46

@pllim, I am seeing matching values.  You `PixTable` cutout looks all wrong.  Any chance you can try this locally instead of display-back (although that shouldn't matter...).

**Comment by ejeschke** [comment]
> Maybe your Travis CI was still using GitHub Services? 

github shows a web hook registered for Travis. History of events shows the hooks being called.  Travis builds show that the hooks are triggering builds.

@pllim, is `astropy` using the "Travis CI by travis-pro" github "app"?  Seems like that may be necessary for the result to show up in the "checks" area of the PR pages...

**Comment by pllim** [comment]
Re: `PixValue` -- It is already broken on `master`, so I opened a new issue at #836. Due to COVID-19, I cannot check that same machine physically. `PixValue` works fine on local machine but it is a different OS.

**Comment by pllim** [comment]
Re: segfault -- Also on `master`, see #837

**Comment by pllim** [comment]
I think the blockers are all not related to this PR. Would still be nice to see Travis CI actually reporting back before merge but also not a blocker.

**Comment by ejeschke** [comment]
> Would still be nice to see Travis CI actually reporting back before merge but also not a blocker.

You can see the Travis result [passing here](https://travis-ci.org/github/ejeschke/ginga/builds/678835772).  Did `astropy` do anything when migrating from the service to the web hook?

**Comment by pllim** [comment]
I can't speak for `astropy` but I switched my projects to GitHub Apps.

`Settings -> Integrations -> Installed GitHub Apps`

**Comment by pllim** [comment]
I also see it under `Settings -> Webhook -> https://notify.travis-ci.org/ (...)`

**Comment by ejeschke** [comment]
> I also see it under `Settings -> Webhook -> https://notify.travis-ci.org/ (...)`

So that is that is confusing, because this is the exact webhook that is shown in Ginga repo settings.  I'm wondering if I also need to install the github app in order to get the result to show up in the checks tab.

**Comment by pllim** [comment]
Well, doesn't hurt to try. The webhook is obviously sending jobs to Travis CI, just somehow not reporting back.

**Comment by ejeschke** [comment]
Thanks for filing the new issues, @pllim.  In the interest of working through the backlog of PRs, I'm going to merge this one.  I will add some more documentation to clarify usage of `Collage` before we make the next release.

**Comment by pllim** [comment]
Sounds good. Thanks!

**Pull request merged**
