### PR TITLE
Update astropy-helpers to v2.0

### PR DESCRIPTION
**Pull request by bsipocz**
This is an automated update of the astropy-helpers submodule to v2.0. This includes both the update of the astropy-helpers sub-module, and the ``ah_bootstrap.py`` file, if needed.

*This is intended to be helpful, but if you would prefer to manage these updates yourself, or if you notice any issues with this automated update, please let @bsipocz or @astrofrog know!*

### CODE REVIEW

**Comment by ejeschke** [comment]
Any gotchas here, @pllim?  I assume this supercedes #523. 

Does this affect our astropy version dependency, as per discussion in #487 ?

**Comment by pllim** [comment]
I see that Python 2.6 support is dropped but Sphinx 1.6 support is added. However, I am unclear on the minimum Astropy version that would work with this, perhaps @bsipocz or @astrofrog can comment?

**Comment by bsipocz** [comment]
@pllim - 1.0.x should still work as we hasn't removed the test compatibility stuff from the helpers. Python 2.6 and python 3.3 support was dropped, including some workarounds so I wouldn't be surprised if those would produce errors (though maybe they still work).

**Comment by bsipocz** [comment]
Btw in astropy we also dropped numpy support for <1.9 as those are pretty old, so at some point you may want to revise those as well (just to make your life of maintenance easier).

**Comment by pllim** [comment]
I can see from another repo (`spherical-geometry`) that Python 2.6 and 3.3 no longer works, so I can confirm that much. @ejeschke , are you okay with this? I have no problem with asking user to upgrade but I understand that pipeline or observatory control might be stricter.

**Comment by ejeschke** [comment]
I think it is somewhere in the docs (or maybe just the pypi info) that we support 2.7 and 3.4+.  So I am ok with no support for 2.6 and 3.3.

**Comment by pllim** [comment]
LGTM as long as you are okay with dropping support for the older versions mentioned above, @ejeschke . 👍

**Comment by bsipocz** [comment]
Oh, one more thing. Apparently this release accidentally screwed up support for older sphinx (<1.5). So if you expect that being an issue, I suggest to wait for the fix in 2.0.1

**Comment by pllim** [comment]
Sphinx is only used for RTD, so as long as 1.6 can be used over there, this should not be an issue. As for local doc build, one can always update Sphinx to 1.6. It is not a deal breaker for me but @ejeschke should make the call. Thanks for the info, @bsipocz !

**Comment by pllim** [comment]
Superseded by #537

**Pull request closed without merging**
