### PR TITLE
Fix import error in RTD build

### PR DESCRIPTION
**Pull request by pllim**
This is a follow-up of #305. I forgot the quirks of building on RTD. I already made sure this works on my own [RTD branch](http://gingabranchlim.readthedocs.org/en/fix-rtd-import/manual/plugins_global/changehistory.html).

Note: @ejeschke , you have to ensure you have the following settings:

screenshot
...
screenshot-1

### CODE REVIEW

**Comment by pllim** [comment]
p.s. The correct path is `doc/rtd-pip-requirements`. I updated the screenshot above to reflect this.

**Comment by pllim** [comment]
Ops, I forgot I also added the same thing in #313. @ejeschke , you don't have to merge this if you plan to merge #313. But I am keeping this open until this file is in there one way or another. FYI.

**Comment by ejeschke** [comment]
ok, lets leave it for #313.  I plan to merge that after a careful check.

**Comment by pllim** [comment]
@ejeschke , I notice that Ginga RTD build is failing. You don't have to merge this PR, but could you please double check that the admin settings are as stated above? I [cannot reproduce the failure](https://readthedocs.org/projects/gingabranchlim/builds/3973773/) on my branch that is synced with your master.

**Comment by pllim** [comment]
Here is the HTML doc from my branch's successful RTD build: http://gingabranchlim.readthedocs.io/en/master/

**Pull request closed without merging**
