### PR TITLE
Implement basic interface to ASDF and GWCS

### LINKED ISSUE #327: Add option to use gWCS
@mcara suggested that Ginga should add the option to support [gWCS](http://gwcs.readthedocs.io/en/latest/) (https://github.com/spacetelescope/gwcs) for future JWST support. I am just opening an issue here so I don't forget that this request happened.

c/c @larrybradley, @nden, @stscieisenhamer

### PR DESCRIPTION
**Pull request by pllim**
This might still need unreleased ASDF and GWCS. It definitely requires Astropy 3.1 or later. But it does work, I propose that we merge this at its current state and improve it in future PRs, as needed. (Limited support is better than zero support?)

Fix #327

cc @hcferguson , @nden , and @drdavella

**TODO:**

- [x] Test with some files: FITS with FITS WCS, ADSF with GWCS, ASDF-in-FITS with GWCS
- [x] Write tests.

**Open Questions:**

* `AstroImage.load_asdf()` -- How to let user specify where data and WCS are in ASDF?
* No way to load JWST data in a meaningful way without JWST data models hidden within JWST pipeline.

**Known issues (future PRs):**

* ~~`Compass` does not work.~~ 
* `WCSAxes` does not work. But this could be an issue with the test image rather than the plugin; need a better dataset to be sure.
* ~~Data cube not fully supported. `LineProfile` does not fully work.~~
* Very limited testing done.
* Documentation deferred to future PR when this is more stable.

### CODE REVIEW

**Comment by ejeschke** [comment]
There are edits to two files needed still (@pllim will add them to the PR).  Result looks like this with the sample ASDF file we got from @nden:
screenshot from 2018-11-15 10-19-17

**Comment by ejeschke** [comment]
Nice sample image, @nden!

**Comment by pllim** [comment]
@ejeschke I already added them in second commit and gave you credit. Did I miss something? I still need to make sure the GWCS methods are working as expected though.

**Comment by ejeschke** [comment]
I just sent you some changes to them, that are needed.

**Comment by nden** [comment]
Thanks for adding support for gwcs @ejeschke and @pllim! 
First package to do so!

**Comment by pllim** [comment]
I tried to open an ASDF file directly using "imaging_wcs.asdf" that @nden provided but ran into the following error using Python 3.7.1, `asdf` 2.3.0 (and also tried 2.4.0.dev1660), and `gwcs` 0.10.dev429.

```
$ python example_asdf.py 
Error in scaling: window size undefined
Error in scaling: window size undefined
.../asdf/asdftypes.py:14: AsdfDeprecationWarning: The module asdf.asdftypes
    has been deprecated and will be removed in 3.0. Use asdf.types instead.
  "Use asdf.types instead.", AsdfDeprecationWarning)
Failed to initialize image: num_points not in range 0-0
Traceback:
  File ".../ginga/ImageView.py", line 795, in _image_set_cb
    self.apply_profile_or_settings(image)
  File ".../ginga/ImageView.py", line 875, in apply_profile_or_settings
    self.auto_levels()
  File ".../ginga/ImageView.py", line 2648, in auto_levels
    loval, hival = autocuts.calc_cut_levels(image)
  File ".../ginga/AutoCuts.py", line 409, in calc_cut_levels
    AutoCutsError("num_points not in range 0-%d" % (total_points))

Error redrawing image: new scale would exceed pixel max; scale unchanged
Traceback:
  File ".../ginga/ImageView.py", line 1274, in redraw_now
    self.redraw_data(whence=whence)
  File ".../ginga/ImageView.py", line 1316, in redraw_data
    rgbobj = self.get_rgb_object(whence=whence)
  File ".../ginga/ImageView.py", line 1516, in get_rgb_object
    win_wd, win_ht)
  File ".../ginga/ImageView.py", line 1584, in _calc_bg_dimensions
    raise ImageViewError("new scale would exceed pixel max; scale unchanged")
```

**Comment by ejeschke** [comment]
I think right now it only works with the ASDF embedded in FITS.  I just tested in a new environment with the latest `asdf`, `gwcs` and `astropy` from github.  It opens the `cropped_asdfinfits2.fits` file.

**Comment by ejeschke** [comment]
@pllim, just checked the size of the `imaging_wcs.asdf` file.  It is 2.2KB, whereas the asdf embedded in fits file is 1.4MB.  Does the ASDF file really have any data or is it just the WCS?

**Comment by drdavella** [comment]
How was that particular ASDF file generated?

**Comment by pllim** [comment]
@nden gave it to us.

**Comment by pllim** [comment]
@ejeschke , this does not yet completely replace `'astropy'` mode. See "questions" and "known issues" in my original post above, which is updated.

But if this looks like a good enough start for you, we can merge and address the rest later to avoid merge conflicts.

**Comment by ejeschke** [comment]
> See "questions" and "known issues" in my original post above, which is updated.

@pllim, can you elaborate on why the named plugins don't work? Any insights?

**Comment by ejeschke** [comment]
And can you put a cube file with the problems in the Box ginga folder?

**Comment by pllim** [comment]
@ejeschke , I am not sure. I have been staring at this for a few days and I need a break. There were a string of traceback and I can make little sense of without code diving. I guess it is the subtleties in the ways that WCS methods are called in different places?

For the cube, it is ngc6946.fits that you gave me.

**Comment by ejeschke** [comment]
@pllim, compass and `LineProfile` seem to be working for me with this PR and `ngc6946.fits`.  WCSAxes does not work with the cube, but I don't think that is related this PR.  That is just a case of the code not dealing with the result of a coordinate-to-pixel lookup in a cube.

**Comment by pllim** [comment]
Using this PR, when opening "image_wcs.asdf" in reference viewer, I see:
```
2018-12-08 09:21:00,327 | E | wcs_astropy_ape14.py:127 (radectopix) |
  Error calculating radectopix: __call__() missing 1 required positional argument: 'delta_C'
2018-12-08 09:21:00,327 | W | Pan.py:305 (set_image) |
  Can't calculate wcs compass: __call__() missing 1 required positional argument: 'delta_C'
2018-12-08 09:21:00,328 | E | Pan.py:310 (set_image) | Traceback:
  File "...\ginga\rv\plugins\Pan.py", line 294, in set_image
    wcs.add_offset_xy(image, x, y, 1.0, 1.0)
  File "...\ginga\util\wcs.py", line 757, in add_offset_xy
    x2, y2 = image.radectopix(ra2_deg, dec2_deg)
  File "...\ginga\AstroImage.py", line 416, in radectopix
    naxispath=self.revnaxis)
  File "...\ginga\util\wcsmod\wcs_astropy_ape14.py", line 128, in radectopix
    raise common.WCSError(e)
```

With the same image, I see this when I open the `WCSAxes` plugin and the lines are not showing as expected:
```
2018-12-08 09:23:39,379 | E | ImageView.py:1288 (redraw_now) |
  Error redrawing image: float division by zero
2018-12-08 09:23:39,381 | E | ImageView.py:1293 (redraw_now) | Traceback:
  File "...\ginga\ImageView.py", line 1274, in redraw_now
    self.redraw_data(whence=whence)
  File "...\ginga\ImageView.py", line 1319, in redraw_data
    self.private_canvas.draw(self)
  File "...\ginga\canvas\DrawingMixin.py", line 722, in draw
    super(DrawingMixin, self).draw(viewer)
  File "...\ginga\canvas\CompoundMixin.py", line 143, in draw
    obj.draw(viewer)
  File "...\ginga\canvas\DrawingMixin.py", line 722, in draw
    super(DrawingMixin, self).draw(viewer)
  File "...\ginga\canvas\CompoundMixin.py", line 143, in draw
    obj.draw(viewer)
  File "...\ginga\canvas\DrawingMixin.py", line 722, in draw
    super(DrawingMixin, self).draw(viewer)
  File "...\ginga\canvas\CompoundMixin.py", line 143, in draw
    obj.draw(viewer)
  File "...\ginga\canvas\types\astro.py", line 962, in draw
    self.objects = self._calc_axes(viewer, image, cur_rot, cur_swap)
  File "...\ginga\canvas\types\astro.py", line 821, in _calc_axes
    d_ra_step = ra_size * self._pix_res / min_imsize
```

Using "ngc6946.fits", in `MultiDim` plugin, the play button (single triangle) does not work:
```
Error making callback 'activated': float division by zero
Traceback:
  File "...\ginga\misc\Callback.py", line 134, in make_callback
    res = method(*cb_args, **cb_kwdargs)

  File "...\ginga\rv\plugins\MultiDim.py", line 138, in <lambda>
    ('play', 'play', lambda w: self.play_start()),

  File "...\ginga\rv\plugins\MultiDim.py", line 490, in play_start
    self.play_next(self.timer)

  File "...\ginga\rv\plugins\MultiDim.py", line 511, in play_next
    fps = 1.0 / (time_start - self.play_last_time)
```

Good news is that, like you said, `LineProfile` does work. I was confused because I was testing it on my tiny laptop with Ginga not maximized and did not see the marker move when I click "next slice" (double triangles) on `MultiDim`. I see it move when I have Ginga maximized.

**Comment by pllim** [comment]
UPDATE: @ejeschke , I address the `MultiDim` error in my latest commit (as if this posting). However, advise on how to debug and fix the rest (see https://github.com/ejeschke/ginga/pull/719#issuecomment-445475988) is much appreciated. Thank you!

**Comment by ejeschke** [comment]
> Using "ngc6946.fits", in MultiDim plugin, the play button (single triangle) does not work

@pllim, using the latest version of this PR with "ngc6946.fits", the play button works perfectly for me.  Looking at the error message you posted above, maybe you could take the line:
```python
fps = 1.0 / (time_start - self.play_last_time)
```
and change it to:
```python
fps = 1.0 / max(1, time_start - self.play_last_time)
```

**Comment by ejeschke** [comment]
I think the `WCSAxes` fix can be developed in a separate PR.  Is compass still not working for you, even with an ordinary FITS file?

**Comment by ejeschke** [comment]
Updated calculation in suggestion above.

**Comment by pllim** [comment]
> fps = 1.0 / 1.0 if np.isclose(span, 0.0) else span

Do you mean this instead?
```python
fps = 1.0 / span if not np.isclose(span, 0.0) else span
```

**Comment by ejeschke** [comment]
> > fps = 1.0 / 1.0 if np.isclose(span, 0.0) else span
> 
> Do you mean this instead?
> 
> ```python
> fps = 1.0 / span if not np.isclose(span, 0.0) else 1.0
> ```

That reads better, yes.

**Comment by pllim** [comment]
@ejeschke , I am okay with deferring WCSAxes to a separate PR. However, the compass does not work when I open up "cropped_asdfinfits.fits" (the file from Nadia) in the reference viewer and then use `MultiDim` to switch to the ASDF extension. I mean, the compass appeared on SCI extension but disappeared when ASDF is shown (and some traceback on terminal). Do you see the same thing?

More importantly, I also want to make sure I did not break the `astropy` mode since I removed some dead code from there as well and made a code change that @eteq said would be more performant when it comes to frame transformation.

**Comment by pllim** [comment]
@ejeschke , this is now ready for final review. I agree that we can defer the `WCSAxes` plugin issue as a follow-up PR.

**Comment by pllim** [comment]
@ejeschke , what is the best way to incorporate #649 to this PR? Would you be interested to submit a PR against this PR?

**Comment by ejeschke** [comment]
> what is the best way to incorporate #649 to this PR? Would you be interested to submit a PR against this PR?

That makes sense. Can you rebase this and I'll take a shot at it.

**Comment by pllim** [comment]
I am not sure how to resolve the conflict in Control.py after your refactoring. Is it okay to revert your changes just where the conflict is and then you can fix it properly?

**Comment by ejeschke** [comment]
Let me try to resolve it via a PR on your PR.

**Comment by ejeschke** [comment]
@pllim, getting the following warning:
AsdfDeprecationWarning: The module asdf.asdftypes has been deprecated and will be removed in 3.0. Use asdf.types instead.

**Comment by ejeschke** [comment]
If checks pass, can you try this out @pllim and see if you agree/grok the changes I pushed?

**Comment by ejeschke** [comment]
I think this can be improved a bit, but I suggest doing it in another PR.

**Comment by ejeschke** [comment]
> Do you want to take the honor/blame of merging this when tests pass? :wink: 

@pllim, FFTM :stuck_out_tongue_winking_eye:

**Comment by ejeschke** [comment]
FFTM==Feel Free To Merge

**Pull request merged**
