### PR TITLE
TST: Enable Appveyor CI 

### LINKED ISSUE #712: Appveyor CI?
This repo has `appveyor.yml` but looks like only Travis CI is running. I can't see the repo settings. @ejeschke , is Appveyor simply never enabled or is it broken? A check in the settings should make this clear.

### PR DESCRIPTION
**Pull request by pllim**
Fix #712 

Results would appear in https://ci.appveyor.com/project/pllim/ginga

### CODE REVIEW

**Comment by pllim** [comment]
@ejeschke , looks like we need to set up the webhook URL on repo settings, which I cannot see.

**Comment by ejeschke** [comment]
@pllim, do you have settings for payload URL and so forth?

**Comment by pllim** [comment]
Looks like Appveyor webhook works! 😄 

https://ci.appveyor.com/project/pllim/ginga

It is running now from the latest `master` commit. If it fails, then maybe this PR would help fix it.

**Comment by pllim** [comment]
I might tag on #747 here when I get the chance, so I can show off all the badges!

**Comment by pllim** [comment]
UPDATE: Oh, it passed on `master`, so looks like this PR is not necessary. Never mind!

https://ci.appveyor.com/project/pllim/ginga/builds/22505035

**Pull request closed without merging**
