### PR TITLE
Prepare for removal of dual viewer/canvas object

### PR DESCRIPTION
**Pull request by ejeschke**
- updates all example programs to avoid using the combination object
- will allow us to make #973 a smaller PR
- this doesn't actually deprecate anything

### CODE REVIEW

**Comment by ejeschke** [comment]
When you have time, @pllim. This is just updating example programs and introduces no feature changes to reference viewer or any deprecations.

**Review by pllim — APPROVED** [review]
Looks uncontroversial enough. Thanks!

Feel free to merge. 😸

**Comment by pllim** [comment]
"This branch has conflicts that must be resolved" -- You might want to rebase.

**Comment by ejeschke** [comment]
Thanks, @pllim! Merging.

**Pull request merged**
