### PR TITLE
BUG: Fix moving annulus

### PR DESCRIPTION
**Pull request by pllim**
One of the refactoring broke moving of an existing annulus. This should fix it.

### CODE REVIEW

**Comment by ejeschke** [comment]
Hmm, it would be nice if derived types of this sort didn't have to manage moving all their own objects.  Let me take a quick look...

**Comment by ejeschke** [comment]
@pllim, fixed in commit f33e409b77f251a7ef90e1bdf81fa361f7fd0855.  The `super` call had not been updated correctly in the refactor.

**Comment by ejeschke** [comment]
Thanks for catching this!

**Comment by ejeschke** [comment]
Sorry, hang on, let me merge the commit...

**Comment by pllim** [comment]
Thanks, @ejeschke , but that commit is not on `master`. Where is it?

**Pull request closed without merging**
