### PR TITLE
Change deprecated call to contains_arr()

### PR DESCRIPTION
**Pull request by ejeschke**
Changes ``contains_arr()`` to a call to ``contains_pts()``.

### CODE REVIEW

**Comment by ejeschke** [comment]
No hurry on this one at all, @pllim. The call will not be removed for a couple of releases yet.

**Review by pllim — APPROVED** [review]
Looks uncontroversial enough. Thanks!

**Comment by pllim** [comment]
(Feel free to merge.)

**Comment by ejeschke** [comment]
Thanks for the review, @pllim!

**Pull request merged**
