### PR TITLE
Remove astropy-helpers

### LINKED ISSUE #758: Remove dependency on astropy-helpers
Following the ideas in [APE 52](https://github.com/astropy/astropy-APEs/pull/52), we should remove the `astropy-helpers` dependency and move to the standard Python ecosystem tools.  Since Ginga is a pure-Python package, this should be relatively straightforward, following the suggestions at the link.

### PR DESCRIPTION
**Pull request by pllim**
Fix #758 

Also tagged 3.1.dev as part of this work (see tags in this repo), as `setuptools_scm` requires dev tag after a release for proper version tracking.

### CODE REVIEW

**Comment by pllim** [comment]
@ejeschke , the tests passed but you might wanna take this PR for a spin before merge.

**Comment by ejeschke** [comment]
> Also tagged 3.1.dev as part of this work (see tags in this repo), as setuptools_scm requires dev tag after a release for proper version tracking.

Can you elaborate a little?  Do we have to update the tag to be the same as `master`?

**Comment by pllim** [comment]
Sure, please see https://github.com/astropy/astropy-APEs/blob/master/APE17.rst#version-helpers , specifically:

"Switching to setuptools_scm requires minimal configuration, which is well described in its documentation and we therefore do not repeat here. However, one subtlety is that since it relies on tags to determine versions, for packages such as the core astropy package which have all their tags on branches (at least in recent years), we will need to add a 'developer' tag on master straight after branching, e.g., after creating a v4.0.x branch we should tag the next commit on master as v4.1.dev. In any case, the documentation about how to release the core package will need to be updated to reflect the use of setuptools_scm."

**Comment by ejeschke** [comment]
> e.g., after creating a v4.0.x branch we should tag the next commit on master as v4.1.dev

Is it necessary to update the tag then for every commit to `master`?

**Comment by pllim** [comment]
No need to tag for every commit to master. The dev tag is only needed *after* a new release, so that `setuptools_scm` knows how to create versions like "4.1.dev3", where "3" means "3 commits since 4.1.dev". Does that make sense?

As I said, I already tagged 3.1.dev for this time around, so there is no need to tag dev again until the next time you make a release. 😸

**Comment by pllim** [comment]
`NUMPY_VERSION=1.14` job timed out. Do we really need it?

**Comment by ejeschke** [comment]
I don't think so.  I was wondering about that--seems like `conda` no longer supports it?  I think current version is something like 1.17?

**Comment by pllim** [comment]
Numpy is now at 1.18.x

**Comment by pllim** [comment]
Phew. Tests finally pass. @ejeschke , if you are happy with this PR, please merge it. Thanks!

**Comment by ejeschke** [comment]
@pllim, how do we run tests now? 
```python
$ pytest ginga/tests
Traceback (most recent call last):
  File "/home/eric/miniconda3/envs/py37/lib/python3.7/site-packages/_pytest/config/__init__.py", line 372, in _getconftestmodules
    return self._path2confmods[path]
KeyError: local('/home/eric/Git/Ginga/ginga/tests')

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/eric/miniconda3/envs/py37/lib/python3.7/site-packages/_pytest/config/__init__.py", line 403, in _importconftest
    return self._conftestpath2mod[conftestpath]
KeyError: local('/home/eric/Git/Ginga/ginga/conftest.py')

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/eric/miniconda3/envs/py37/lib/python3.7/site-packages/_pytest/config/__init__.py", line 409, in _importconftest
    mod = conftestpath.pyimport()
  File "/home/eric/miniconda3/envs/py37/lib/python3.7/site-packages/py/_path/local.py", line 668, in pyimport
    __import__(modname)
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/home/eric/miniconda3/envs/py37/lib/python3.7/site-packages/_pytest/assertion/rewrite.py", line 226, in load_module
    py.builtin.exec_(co, mod.__dict__)
  File "/home/eric/Git/Ginga/ginga/conftest.py", line 25, in <module>
    TESTED_VERSIONS[packagename] = version
NameError: name 'TESTED_VERSIONS' is not defined
ERROR: could not load /home/eric/Git/Ginga/ginga/conftest.py
```
I tried various combinations of:
```bash
$ pytest ginga/tests
$ pytest --pyargs ginga
$ tox -e test
```

**Comment by ejeschke** [comment]
I was able to run the tests by making a `tox.ini` file as follows:
```ini
[testenv:test]
deps =
  pytest-astropy
commands =
  pytest ginga/tests
```
This was the output:
```bash
$ tox -e test
GLOB sdist-make: /home/eric/Git/Ginga/setup.py
test create: /home/eric/Git/Ginga/.tox/test
test installdeps: pytest-astropy
test inst: /home/eric/Git/Ginga/.tox/.tmp/package/1/ginga-0.0.0.zip
test installed: astropy==4.0,attrs==19.3.0,ginga==0.0.0,hypothesis==5.1.3,importlib-metadata==1.4.0,more-itertools==8.0.2,numpy==1.18.1,packaging==20.0,pluggy==0.13.1,psutil==5.6.7,py==1.8.1,pyparsing==2.4.6,pytest==5.3.2,pytest-arraydiff==0.3,pytest-astropy==0.7.0,pytest-astropy-header==0.1.2,pytest-doctestplus==0.5.0,pytest-openfiles==0.4.0,pytest-remotedata==0.3.2,QtPy==1.9.0,six==1.13.0,sortedcontainers==2.1.0,wcwidth==0.1.8,zipp==0.6.0
test run-test-pre: PYTHONHASHSEED='3818642932'
test run-test: commands[0] | pytest ginga/tests
/home/eric/Git/Ginga/.tox/test/lib/python3.7/site-packages/astropy/config/configuration.py:557: ConfigurationMissingWarning: Configuration defaults will be used due to OSError:Could not find unix home directory to search for astropy config dir on None
  warn(ConfigurationMissingWarning(msg))
============================= test session starts ==============================
platform linux -- Python 3.7.3, pytest-5.3.2, py-1.8.1, pluggy-0.13.1
cachedir: .tox/test/.pytest_cache

Running tests with ginga version 3.1.dev37+g17ab87df.
Running tests in ginga/tests.

Date: 2020-01-10T16:00:16

Platform: Linux-4.15.0-66-generic-x86_64-with-debian-buster-sid

Executable: /home/eric/Git/Ginga/.tox/test/bin/python

Full Python Version: 
3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0]

encodings: sys: utf-8, locale: UTF-8, filesystem: utf-8
byteorder: little
float info: dig: 15, mant_dig: 15

Package versions: 
Numpy: 1.18.1
Scipy: not available
Matplotlib: not available
h5py: not available
Pandas: not available
Astropy: 4.0
scikit-image: not available
astropy-helpers: 4.0.1

Using Astropy options: remote_data: none.

rootdir: /home/eric/Git/Ginga, inifile: setup.cfg
plugins: hypothesis-5.1.3, openfiles-0.4.0, astropy-header-0.1.2, doctestplus-0.5.0, arraydiff-0.3, remotedata-0.3.2
collected 98 items / 1 skipped / 97 selected                                   

ginga/tests/test_ImageView.py ..                                         [  2%]
ginga/tests/test_aimg.py ....                                            [  6%]
ginga/tests/test_cmap.py ........                                        [ 14%]
ginga/tests/test_colordist.py ........                                   [ 22%]
ginga/tests/test_colors.py .....................                         [ 43%]
ginga/tests/test_imap.py ........                                        [ 52%]
ginga/tests/test_iohelper.py ..                                          [ 54%]
ginga/tests/test_iqcalc.py ....                                          [ 58%]
ginga/tests/test_trcalc.py ..                                            [ 60%]
ginga/tests/test_wcs.py sss..sss..sss..sss.....................          [100%]

======================== 86 passed, 13 skipped in 1.00s ========================
___________________________________ summary ____________________________________
  test: commands succeeded
  congratulations :)
```
Should we add a `tox` file to the repository, or is there a better way?

**Comment by pllim** [comment]
Feel free to add the tox file. Thanks! :)

**Pull request merged**
