### PR TITLE
Documentation fixes

### PR DESCRIPTION
**Pull request by rupak0577**
Updated plugin docs for MultiDim and Cuts.

### CODE REVIEW

**Comment by nabobalis** [comment]
Is this all the documentation you plan to add?

**Comment by rupak0577** [comment]
@nabobalis I will add the rest as soon as the other branches are in their final state.

**Comment by nabobalis** [comment]
@rupak0577 Is there anything else you would like to add? 
@ejeschke This is should be ok to merge once the other two PRs are accepted.

**Comment by ejeschke** [comment]
Sounds good.

**Comment by ejeschke** [comment]
Merged with some light editing.

**Pull request merged**
