### PR TITLE
Fix for github issue #257

### LINKED ISSUE #257: Sorting by numbers with TreeView
`TreeView` does not sort numeric column properly because it internally stores the numbers as strings. I tried passing in numbers in `set_tree()` but that didn't work. Also tried padding them with leading spaces or filler characters, also didn't work.

How do I fix this?

screenshot

### PR DESCRIPTION
**Pull request by ejeschke**
- possible fix for an issue sorting the TreeWidget in Qt backend

EDIT: Fix #257 

EDIT: Fix spacetelescope/stginga#83

### CODE REVIEW

**Comment by ejeschke** [comment]
@pllim, had an urgent need to fix #257.  Can you check your plugins that use TreeView and see if it is doing the right things?  We can maybe find a less hacky fix later but this seems to do the job.

**Comment by ejeschke** [comment]
Looks like gotta fix a couple pep8 issues...

**Comment by pllim** [comment]
Before 

screenshot from 2018-08-27 12-22-53

After

screenshot from 2018-08-27 12-18-58

:tada:

**Comment by ejeschke** [comment]
:+1:  Merging.

**Pull request merged**
