### PR TITLE
Fix Qt/PySide help crash

### LINKED ISSUE #841: Segfault when closing Ginga Help window (Qt, PySide backends)
Platform: Linux with PySide2 as the Qt environment

When exiting Ginga, there is a segmentation fault, but only if a Help button has been pressed during the session AND the Help window is still open when quitting Ginga.

### PR DESCRIPTION
**Pull request by ejeschke**
(Fix #841)

### CODE REVIEW

**Comment by ejeschke** [comment]
@pllim, this prevents crash when closing Help window in Qt/PySide.  There is still a crash on program exit in PySide if you leave the Help window open until program exit, but I think that moves the problem back into lower priority. Qt backend is fine whether you close the Help window right away or leave it open until program exit. It seems the QWebView widget is a bit sensitive.

**Comment by pllim** [comment]
I cannot test this myself due to #837 , so I guess I'll just have to trust you on this one. FFTM

**Comment by ejeschke** [comment]
> I cannot test this myself due to #837

Sorry, @pllim, don't understand this comment. Meaning you can't reproduce the crash when you press the Close button on `Help`?

**Comment by pllim** [comment]
Sorry for the confusion. I meant, I still get segfault even if this patch, but I think it is a different problem?

**Comment by ejeschke** [comment]
Ah, right.  Reviewing that issue, I think this will solve the problem @rendinam saw with `PySide`.  Ok, merging.

**Pull request merged**
