### PR TITLE
Updates to mode handling

### PR DESCRIPTION
**Pull request by ejeschke**
This modifies the mode handling of the basic ginga widget slightly to
fix an issue with overlapping names for triggers for events (e.g.
left arrow key vs. left mouse button).  It also adds the following
capabilities:

- when in "dist", "cmap" or "cuts" mode, you now have the choice of
  scrolling or using the up/down arrow keys, or the b/n keys when
  setting the preference
- intensity map can be set in "cmap" mode using the k/l keys, and
  restored with "i"
- when in "cmap" mode you can toggle a color bar overlay with "c"
- when in "pan" or "freepan" mode, you can use the arrow keys to pan;
  holding down ctrl, shift or both will adjust the amount of the pan
- when in "pan" or "freepan" mode there is a new feature where you can
  save the current zoom setting by pressing "z", and then use the
  backquote key to zoom out to the whole image, and then the "1" key
  to pan to the position under the cursor and restore the zoom level

This PR also fixes two issues:
- as per #357 this suppresses the warning messages for non-existent
    methods in Bindings
- there is an update to ImageViewTk for recent changes to PIL

### CODE REVIEW

**Comment by ejeschke** [comment]
@pllim, can you please try this PR with `stginga`?  Although I don't expect any problems unless you are making explicit calls to the 'Bindmap` object.  This adds some nice features to several modes in the basic widget, all of which are documented in the quickref.

This also silences the messages referenced in #357

**Comment by ejeschke** [comment]
Updated with slight modifications to mode lock handling.

**Comment by pllim** [comment]
Thanks, @ejeschke ! I'll take your PRs for a spin on Monday.

**Comment by pllim** [comment]
@ejeschke , I tested this and #361 together and didn't find any problem on my end. Thank you! :+1:

**Pull request merged**
