### PR TITLE
Add E741 to white-list to fix PEP8 test

### PR DESCRIPTION
**Pull request by pllim**
Follow up of #589

### CODE REVIEW

**Comment by pllim** [comment]
Huh, it keeps finding new things to complain about, although I think these actually should be fixed.
```
ginga/rv/plugins/Catalogs.py:352:9: E722 do not use bare except'

ginga/rv/plugins/Compose.py:240:46: E127 continuation line over-indented for visual indent

ginga/rv/plugins/Compose.py:244:1: W293 blank line contains whitespace

ginga/rv/plugins/Compose.py:260:1: W293 blank line contains whitespace

ginga/rv/plugins/Compose.py:403:1: W293 blank line contains whitespace

ginga/util/addons.py:8:1: E302 expected 2 blank lines, found 1

ginga/util/addons.py:194:28: E226 missing whitespace around arithmetic operator

ginga/util/addons.py:194:34: E226 missing whitespace around arithmetic operator

ginga/util/addons.py:195:28: E226 missing whitespace around arithmetic operator

ginga/util/addons.py:195:34: E226 missing whitespace around arithmetic operator
```

**Comment by ejeschke** [comment]
Those are new errors introduced by me!  I need to start running flake8 on my commits--probably a good idea.

**Comment by ejeschke** [comment]
Except for the `Catalogs` one--I don't think that is mine.

**Comment by pllim** [comment]
The `Catalogs` one could be an earlier fix that was lost in rebase/merge, but it is just a guess.

**Comment by pllim** [comment]
It is passing now! 😄

**Comment by ejeschke** [comment]
@pllim, so command to check should be:
```bash
flake8 ginga --count $FLAKE8_OPT
```
where `FLAKE8_OPT` is "--select=E265,E266,E501,..."

**Comment by ejeschke** [comment]
Ok, merging to get the build passing.

**Comment by pllim** [comment]
No, actually `$FLAKE8_OPT` is unnecessary; that is why I removed it. As long as you have a `[flake8]` section in `setup.cfg`, `flake8` should be smart enough to pick that up.

**Comment by ejeschke** [comment]
So for running it manually, it would be
```bash
python setup.py ???
```

**Comment by pllim** [comment]
No, `flake8 ginga/something/something.py` should be enough. I actually use `flycheck` with my Emacs, so it checks automatically. You can probably set up a similar thing with your favorite IDE.

**Pull request merged**
