### PR TITLE
Add a new Ginga SVG icon

### LINKED ISSUE #804: Design an icon for ginga?
Hi,

thanks for the new version; I am just preparing its upload as a Debian package.
One request for perfection: it would be nice if ginga would have an icon that can be displayed f.e. in task bars. [`ginga-512x512.png`](https://github.com/ejeschke/ginga/blob/b33e09fff87921d10dc85fd1b0735a90ab102bca/ginga/icons/ginga-512x512.png) is too big for this.

Cheers
Ole

### PR DESCRIPTION
**Pull request by ejeschke**
Adds a new SVG based icon for Ginga.

- fixes #804

### CODE REVIEW

**Comment by ejeschke** [comment]
@olebole, a couple questions for you, if you'd be so kind:
- do I need to save the SVG icon with a "preferred size" (I know they are vector drawings, but it seems there is some "default size" set inside it)? Or is the one that I have added here ok?
- how should I change `ginga.desktop` so that the icon path is set correctly?

**Comment by pllim** [comment]
So with this patch, this this file outdated?

https://github.com/ejeschke/ginga/blob/master/ginga/icons/ginga-512x512.png

**Comment by olebole** [comment]
For, this looks nice. I don't need a "preferred size".
In `ginga.desktop`, you just need to add `ginga.svg` as you did, and install the icon file where it can be found (`/usr/share/pixmaps` on Debian).

**Comment by ejeschke** [comment]
> and install the icon file where it can be found (/usr/share/pixmaps on Debian).

Can your Debian packaging script for apt put it in the right place if it is in ginga/icons in the repo or ginga/icons in the PyPI package?

**Comment by ejeschke** [comment]
> So with this patch, this this file outdated?
> 
> https://github.com/ejeschke/ginga/blob/master/ginga/icons/ginga-512x512.png

Possibly. I'll do a quick check to see if it is used anywhere and add its removal to this PR if not.

**Comment by olebole** [comment]
@ejeschke 
> Can your Debian packaging script for apt put it in the right place if it is in ginga/icons in the repo or ginga/icons in the PyPI package?

The Debian package will put it to the right place, so after "apt install ginga" all will be fine.

**Comment by ejeschke** [comment]
@pllim, are you ok with the design? If not, maybe accept for now and we figure out a different one later?

**Comment by pllim** [comment]
I don't have any opinion on the logo. Feel free to merge. Thanks!

**Comment by ejeschke** [comment]
`ginga-512x512.png` is currently used by one of the examples.  We will keep it in the repo for the present.

**Comment by ejeschke** [comment]
Thank you @pllim and @olebole!

**Pull request merged**
