### PR TITLE
Add more WCS tests

### PR DESCRIPTION
**Pull request by pllim**
This is a precursor for #327 . I need more tests so I would know GWCS works properly in Ginga-land.

### CODE REVIEW

**Comment by pllim** [comment]
@ejeschke , for efficiency's sake, I am considering refactoring this whole test module to use something like https://docs.pytest.org/en/latest/example/parametrize.html#a-quick-port-of-testscenarios . Ideally, we only want to create the WCS object once per WCS library of choice.

**Comment by pllim** [comment]
@ejeschke , please review. Especially, I don't know why RADEC converted back to XY cannot obtain X=0 Y=0 (original inputs) within agreement for `numpy.testing.assert_allclose` default settings. I had to tweak the `atol`. Is this expected behavior? See `# TODO: Check with Eric J on this` in the diff to see where those are. Thank you.

**Comment by ejeschke** [comment]
@pllim, did you get errors for `starlink` tests?  I am seeing the tolerance error for that one, but also a couple of `TypeErrors`.

**Comment by pllim** [comment]
I don't have starlink installed. Could you please post traceback?

**Comment by ejeschke** [comment]
Looks like those errors were due to assumptions that the parameters to `datapt_to_wcspt()` and `wcspt_to_datapt()` were numpy arrays.  I submitted a fix to master to fix that, so now I'm just left with either tolerance errors or `NotImplemented` errors.  Taking a look at the tolerance errors now.

**Comment by ejeschke** [comment]
@pllim, here's the test output for python 2.7 (for which I have all of the wcs packages):
```python
$ py.test-2.7 ginga/tests/test_wcs.py
============================= test session starts ==============================
platform linux2 -- Python 2.7.12, pytest-2.8.7, py-1.4.31, pluggy-0.3.1

Running tests with ginga version 2.7.1.dev1897.
Running tests in ginga/tests/test_wcs.py.

Date: 2018-03-21T14:14:03

Platform: Linux-4.4.0-116-generic-x86_64-with-Ubuntu-16.04-xenial

Executable: /usr/bin/python

Full Python Version: 
2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609]

encodings: sys: ascii, locale: UTF-8, filesystem: UTF-8, unicode bits: 20
byteorder: little
float info: dig: 15, mant_dig: 15

Numpy: 1.10.4
Scipy: 0.17.0
Matplotlib: 1.5.1
Pandas: 0.17.1
Astropy: 2.0.dev17896
scikit-image: 0.12.3
Using Astropy options: remote_data: none.

rootdir: /home/eric/Git/Ginga, inifile: 
collected 35 items 

ginga/tests/test_wcs.py FF..FFF.FFF.FFF....................

=================================== FAILURES ===================================
___________________________ test_scalar_2d[kapteyn] ____________________________

modname = 'kapteyn'

    @pytest.mark.parametrize('modname', _wcsmods)
    def test_scalar_2d(modname):
        if modname not in img_dict:
            pytest.skip("WCS '{}' not available".format(modname))
    
        img = img_dict[modname]['2d']
    
        xy_v1 = (120, 100)
        radec_deg_v1 = (300.2308791294835, 22.691653517073615)
    
        # If this works here, should already work for other cases.
        assert img.wcs.has_valid_wcs()
    
        radec = img.pixtoradec(*xy_v1)
        assert_allclose(radec, radec_deg_v1)
    
        xy = img.radectopix(*radec_deg_v1)
        assert_allclose(xy, xy_v1)
    
        gal = img.wcs.pixtosystem(xy_v1, system='galactic')
>       assert_allclose(gal, (60.97030081935234, -3.9706229385605307))
E       AssertionError: 
E       Not equal to tolerance rtol=1e-07, atol=0
E       
E       (mismatch 100.0%)
E        x: array([ 60.970309,  -3.970625])
E        y: array([ 60.970301,  -3.970623])

ginga/tests/test_wcs.py:271: AssertionError
___________________________ test_scalar_2d[starlink] ___________________________

modname = 'starlink'

    @pytest.mark.parametrize('modname', _wcsmods)
    def test_scalar_2d(modname):
        if modname not in img_dict:
            pytest.skip("WCS '{}' not available".format(modname))
    
        img = img_dict[modname]['2d']
    
        xy_v1 = (120, 100)
        radec_deg_v1 = (300.2308791294835, 22.691653517073615)
    
        # If this works here, should already work for other cases.
        assert img.wcs.has_valid_wcs()
    
        radec = img.pixtoradec(*xy_v1)
>       assert_allclose(radec, radec_deg_v1)
E       AssertionError: 
E       Not equal to tolerance rtol=1e-07, atol=0
E       
E       (mismatch 50.0%)
E        x: array([ 300.23087 ,   22.691648])
E        y: array([ 300.230879,   22.691654])

ginga/tests/test_wcs.py:265: AssertionError
_________________________ test_vectorized_2d[kapteyn] __________________________

modname = 'kapteyn'

    @pytest.mark.parametrize('modname', _wcsmods)
    def test_vectorized_2d(modname):
        if modname not in img_dict:
            pytest.skip("WCS '{}' not available".format(modname))
    
        img = img_dict[modname]['2d']
    
        xy_v1 = [(0, 0), (120, 100)]
        radec_deg_v1 = [(300.2381639, 22.68602823),
                        (300.2308791294835, 22.691653517073615)]
        gal_v1 = np.array([(60.96903325, -3.97929572),
                           (60.97030081935234, -3.9706229385605307)])
    
        radec = img.wcs.datapt_to_wcspt(xy_v1)
        assert_allclose(radec, radec_deg_v1)
    
        xy = img.wcs.wcspt_to_datapt(radec_deg_v1)
        # TODO: Check with Eric J on this.
        assert_allclose(xy, xy_v1, atol=7e-5)
    
        gal = img.wcs.datapt_to_system(xy_v1, system='galactic')
        if modname == 'astropy':
            assert_allclose(gal.l.degree, gal_v1[:, 0])
            assert_allclose(gal.b.degree, gal_v1[:, 1])
        else:
>           assert_allclose(gal, gal_v1)
E           AssertionError: 
E           Not equal to tolerance rtol=1e-07, atol=0
E           
E           (mismatch 100.0%)
E            x: array([[ 60.969042,  -3.979298],
E                  [ 60.970309,  -3.970625]])
E            y: array([[ 60.969033,  -3.979296],
E                  [ 60.970301,  -3.970623]])

ginga/tests/test_wcs.py:299: AssertionError
_________________________ test_vectorized_2d[starlink] _________________________

modname = 'starlink'

    @pytest.mark.parametrize('modname', _wcsmods)
    def test_vectorized_2d(modname):
        if modname not in img_dict:
            pytest.skip("WCS '{}' not available".format(modname))
    
        img = img_dict[modname]['2d']
    
        xy_v1 = [(0, 0), (120, 100)]
        radec_deg_v1 = [(300.2381639, 22.68602823),
                        (300.2308791294835, 22.691653517073615)]
        gal_v1 = np.array([(60.96903325, -3.97929572),
                           (60.97030081935234, -3.9706229385605307)])
    
        radec = img.wcs.datapt_to_wcspt(xy_v1)
>       assert_allclose(radec, radec_deg_v1)
E       AssertionError: 
E       Not equal to tolerance rtol=1e-07, atol=0
E       
E       (mismatch 50.0%)
E        x: array([[ 300.238155,   22.686022],
E              [ 300.23087 ,   22.691648]])
E        y: array([[ 300.238164,   22.686028],
E              [ 300.230879,   22.691654]])

ginga/tests/test_wcs.py:288: AssertionError
__________________________ test_vectorized_2d[astlib] __________________________

modname = 'astlib'

    @pytest.mark.parametrize('modname', _wcsmods)
    def test_vectorized_2d(modname):
        if modname not in img_dict:
            pytest.skip("WCS '{}' not available".format(modname))
    
        img = img_dict[modname]['2d']
    
        xy_v1 = [(0, 0), (120, 100)]
        radec_deg_v1 = [(300.2381639, 22.68602823),
                        (300.2308791294835, 22.691653517073615)]
        gal_v1 = np.array([(60.96903325, -3.97929572),
                           (60.97030081935234, -3.9706229385605307)])
    
        radec = img.wcs.datapt_to_wcspt(xy_v1)
        assert_allclose(radec, radec_deg_v1)
    
        xy = img.wcs.wcspt_to_datapt(radec_deg_v1)
        # TODO: Check with Eric J on this.
        assert_allclose(xy, xy_v1, atol=7e-5)
    
>       gal = img.wcs.datapt_to_system(xy_v1, system='galactic')

ginga/tests/test_wcs.py:294: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <wcs_astlib.AstLibWCS object at 0x7fb848b09750>
datapt = [(0, 0), (120, 100)], system = 'galactic', coords = 'data'
naxispath = None

    def datapt_to_system(self, datapt, system=None, coords='data',
                         naxispath=None):
        """
            Map points to given coordinate system.
    
            Parameters
            ----------
            datapt : array-like
                Pixel coordinates in the format of
                ``[[x0, y0, ...], [x1, y1, ...], ..., [xn, yn, ...]]``.
    
            system : str or None, optional, default to 'icrs'
                Coordinate system name.
    
            coords : 'data' or None, optional, default to 'data'
                Expresses whether the data coordinate is indexed from zero
    
            naxispath : list-like or None, optional, defaults to None
                A sequence defining the pixel indexes > 2D, if any
    
            Returns
            -------
            wcspt : array-like
                WCS coordinates in the format of
                ``[[ra0, dec0], [ra1, dec1], ..., [ran, decn]]``.
    
            """
        if self.coordsys == 'raw':
            raise WCSError("No usable WCS")
    
>       raise NotImplementedError
E       NotImplementedError

ginga/util/wcsmod/common.py:283: NotImplementedError
___________________________ test_scalar_3d[kapteyn] ____________________________

modname = 'kapteyn'

    @pytest.mark.parametrize('modname', _wcsmods)
    def test_scalar_3d(modname):
        if modname not in img_dict:
            pytest.skip("WCS '{}' not available".format(modname))
    
        img = img_dict[modname]['3d']
        idxs = (0, 0, 0)
    
        c = img.spectral_coord(idxs)
        assert_allclose(c, -159000.00382)
    
        c = img.pixtoradec(*idxs[:2])
>       assert_allclose(c, (-50.569931842112965, 59.79236398619401))
E       AssertionError: 
E       Not equal to tolerance rtol=1e-07, atol=0
E       
E       (mismatch 50.0%)
E        x: array([ 309.430068,   59.792364])
E        y: array([-50.569932,  59.792364])

ginga/tests/test_wcs.py:314: AssertionError
___________________________ test_scalar_3d[starlink] ___________________________

modname = 'starlink'

    @pytest.mark.parametrize('modname', _wcsmods)
    def test_scalar_3d(modname):
        if modname not in img_dict:
            pytest.skip("WCS '{}' not available".format(modname))
    
        img = img_dict[modname]['3d']
        idxs = (0, 0, 0)
    
        c = img.spectral_coord(idxs)
>       assert_allclose(c, -159000.00382)
E       AssertionError: 
E       Not equal to tolerance rtol=1e-07, atol=0
E       
E       (mismatch 100.0%)
E        x: array(-159.00000382)
E        y: array(-159000.00382)

ginga/tests/test_wcs.py:311: AssertionError
____________________________ test_scalar_3d[astlib] ____________________________

modname = 'astlib'

    @pytest.mark.parametrize('modname', _wcsmods)
    def test_scalar_3d(modname):
        if modname not in img_dict:
            pytest.skip("WCS '{}' not available".format(modname))
    
        img = img_dict[modname]['3d']
        idxs = (0, 0, 0)
    
>       c = img.spectral_coord(idxs)

ginga/tests/test_wcs.py:310: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
ginga/AstroImage.py:310: in spectral_coord
    return self.wcs.spectral_coord(args, coords=coords)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <wcs_astlib.AstLibWCS object at 0x7fb848b23550>, idxs = [0, 0, 0]
coords = (0, 0, 0)

    def spectral_coord(self, idxs, coords='data'):
>       raise common.WCSError("This feature not supported by astWCS")
E       WCSError: This feature not supported by astWCS

ginga/util/wcsmod/wcs_astlib.py:68: WCSError
_________________________ test_vectorized_3d[kapteyn] __________________________

modname = 'kapteyn'

    @pytest.mark.parametrize('modname', _wcsmods)
    def test_vectorized_3d(modname):
        if modname not in img_dict:
            pytest.skip("WCS '{}' not available".format(modname))
    
        img = img_dict[modname]['3d']
    
        xy_v1 = [(0, 0), (120, 100)]
        nxp = [0]
        radec_deg_v1 = [[-5.05699318e+01, 5.97923640e+01],
                        [-5.23010162e+01, 6.05064254e+01]]
        gal_v1 = np.array([(95.62934262, 11.17292729),
                           (95.72174081, 12.28825976)])
    
        radec = img.wcs.datapt_to_wcspt(xy_v1, naxispath=nxp)
>       assert_allclose(radec[:, :2], radec_deg_v1)
E       AssertionError: 
E       Not equal to tolerance rtol=1e-07, atol=0
E       
E       (mismatch 50.0%)
E        x: array([[ 309.430068,   59.792364],
E              [ 307.698984,   60.506425]])
E        y: array([[-50.569932,  59.792364],
E              [-52.301016,  60.506425]])

ginga/tests/test_wcs.py:339: AssertionError
_________________________ test_vectorized_3d[starlink] _________________________

modname = 'starlink'

    @pytest.mark.parametrize('modname', _wcsmods)
    def test_vectorized_3d(modname):
        if modname not in img_dict:
            pytest.skip("WCS '{}' not available".format(modname))
    
        img = img_dict[modname]['3d']
    
        xy_v1 = [(0, 0), (120, 100)]
        nxp = [0]
        radec_deg_v1 = [[-5.05699318e+01, 5.97923640e+01],
                        [-5.23010162e+01, 6.05064254e+01]]
        gal_v1 = np.array([(95.62934262, 11.17292729),
                           (95.72174081, 12.28825976)])
    
        radec = img.wcs.datapt_to_wcspt(xy_v1, naxispath=nxp)
>       assert_allclose(radec[:, :2], radec_deg_v1)
E       AssertionError: 
E       Not equal to tolerance rtol=1e-07, atol=0
E       
E       (mismatch 50.0%)
E        x: array([[ 309.430059,   59.792358],
E              [ 307.698975,   60.506419]])
E        y: array([[-50.569932,  59.792364],
E              [-52.301016,  60.506425]])

ginga/tests/test_wcs.py:339: AssertionError
__________________________ test_vectorized_3d[astlib] __________________________

modname = 'astlib'

    @pytest.mark.parametrize('modname', _wcsmods)
    def test_vectorized_3d(modname):
        if modname not in img_dict:
            pytest.skip("WCS '{}' not available".format(modname))
    
        img = img_dict[modname]['3d']
    
        xy_v1 = [(0, 0), (120, 100)]
        nxp = [0]
        radec_deg_v1 = [[-5.05699318e+01, 5.97923640e+01],
                        [-5.23010162e+01, 6.05064254e+01]]
        gal_v1 = np.array([(95.62934262, 11.17292729),
                           (95.72174081, 12.28825976)])
    
>       radec = img.wcs.datapt_to_wcspt(xy_v1, naxispath=nxp)

ginga/tests/test_wcs.py:338: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <wcs_astlib.AstLibWCS object at 0x7fb848b23550>
datapt = [(0, 0), (120, 100)], coords = 'data', naxispath = [0]

    def datapt_to_wcspt(self, datapt, coords='data', naxispath=None):
        """
            Convert multiple data points to WCS.
    
            Parameters
            ----------
            datapt : array-like
                Pixel coordinates in the format of
                ``[[x0, y0, ...], [x1, y1, ...], ..., [xn, yn, ...]]``.
    
            coords : 'data' or None, optional, default to 'data'
                Expresses whether the data coordinate is indexed from zero.
    
            naxispath : list-like or None, optional, defaults to None
                A sequence defining the pixel indexes > 2D, if any.
    
            Returns
            -------
            wcspt : array-like
                WCS coordinates in the format of
                ``[[ra0, dec0], [ra1, dec1], ..., [ran, decn]]``.
    
            """
        # We provide a list comprehension version for WCS packages that
        # don't support array operations.
        if naxispath:
>           raise NotImplementedError
E           NotImplementedError

ginga/util/wcsmod/common.py:217: NotImplementedError
===================== 11 failed, 24 passed in 1.58 seconds =====================
```

**Comment by ejeschke** [comment]
Looks like we need to make an assertion test that normalizes angles (e.g. add 360 and then mod 360).  For example, the `kapteyn` and `starlink` wcses are giving the angles as negative (but basically equivalent) to the expected result (e.g. -50.569932 vs. 309.430059)

**Comment by ejeschke** [comment]
In the `spectral_coord()` test for `starlink` it looks like the expected units are off by 1000.  This can be fixed by simply modifying the code to divide by 1000 if we can determine that the answers are consistently off by exactly 10**3.

**Comment by ejeschke** [comment]
For the others, it's all just slight variations: sometimes 0.1, sometimes 0.001, etc.  I'm not really a good judge of what the accuracy for WCS should be.  I have heard that there can be rather significant discrepancies between libraries in this regard, so maybe we should choose a rather large tolerance like a tenth of an arcsecond or something.  What do you think?

**Comment by pllim** [comment]
@ejeschke , what do you think about enabling checks using all those supported libraries in Travis CI itself?

I am no WCS libraries expert. IMHO making the tests pass in Ginga's current state should be sufficient given that we have no received complains about WCS accuracy across those libraries? I'll see how I can make those tests more relaxed. Thank you for your feedback.

**Comment by pllim** [comment]
@ejeschke , the tests now pass locally for me with all the WCS libraries being tested. Are you are okay with the `atol`, `rtol`, and `pytest.raises` values?

**Comment by ejeschke** [comment]
This passed all the tests for me.  @pllim if there is no more you want to do on this then I will merge it.

**Comment by pllim** [comment]
I am done with this (for now). :smile:

**Pull request merged**
