### PR TITLE
ENH: Compass N-E to be more robust

### PR DESCRIPTION
**Pull request by pllim**
Compass N-E to be more robust by using small angular offsets when determining compass properties.

This is from https://github.com/spacetelescope/jdaviz/pull/2867 by @astrofrog on the same piece of algorithm we borrowed from Ginga (https://github.com/spacetelescope/jdaviz/blob/main/licenses/GINGA_LICENSE.txt).

### CODE REVIEW

**Comment by pllim** [comment]
You might want to actually see how it renders with your data before merge. Thanks!

**Review by ejeschke — APPROVED** [review]
Thanks, @pllim. I did test the change locally and it seems fine.

**Comment by ejeschke** [comment]
LGTM, FFTM

**Comment by ejeschke** [comment]
:pray:

**Comment by pllim** [comment]
Thanks to @astrofrog !

**Pull request merged**
