### PR TITLE
Fix ginga seg fault

### LINKED ISSUE #65: ginga seg fault with missing ginga_config
In the current `master` version (2.1.20141220052723) in RHEL 6.6 (Santiago) 64-bit, I get segmentation fault and the traceback complains of a missing `ginga_config`. I checked out the source from GitHub and installed it with `python setup.py install --prefix=LOCAL_DIR` command. Am I missing something?
```
2015-01-16 20:47:36,600 | W | main.py:298 (main) | failed to set WCS package preference: 
2015-01-16 20:47:36,600 | W | main.py:310 (main) | failed to set FITS package preference: 
2015-01-16 20:47:36,691 | E | main.py:339 (main) | Error importing Ginga config file: No module named ginga_config
2015-01-16 20:47:36,692 | E | main.py:340 (main) | Traceback:
  File ".../lib/python2.7/site-packages/ginga-2.1.20141220052723-py2.7.egg/ginga/main.py", line 327, in main
    import ginga_config
```

### PR DESCRIPTION
**Pull request by pllim**
Fixes #65

### CODE REVIEW

**Comment by cdeil** [comment]
@pllim travis-ci fails because Astropy now requires jinja2:
https://travis-ci.org/ejeschke/ginga/jobs/47692592#L292

Can you please add it to this `conda install` line in this PR?
https://github.com/ejeschke/ginga/blob/master/.travis.yml#L76

**Comment by ejeschke** [comment]
@pllim, I'm OK to merge this, but it doesn't look like logging module is used in scripts/ginga.  I'd like to know why this fixes the issue?

**Comment by pllim** [comment]
Thanks, @cdeil .

@ejeschke , I am not sure why that worked. I saw this import in your `example2` and noticed that the seg fault happened after it complained about "no handler", so I thought I would just give it a try, and then I got the GUI to run (about 4 out of 5 times). The seg fault gives no other info that I have not mentioned here, so I am not sure how to find out.

We can just leave this open for now and see what happens, if you wish. I can always just use my own copy of your code for now, since apparently I am the only one who has this problem.

**Comment by ejeschke** [comment]
Pushed.  If we solve the issue (Issue65), I'd like to remove the unused import from scripts/ginga.

**Pull request merged**
