### PR TITLE
Add ability to plot tables in PlotViewer

### PR DESCRIPTION
**Pull request by ejeschke**
This PR enhances the Plot viewer and integrates it more cleanly into a channel.

The main changes are that the `Toolbar` and `Info` plugins now adapt their GUI to the type of viewer that is showing in the channel.  The table viewer now has controls to plot columns and this will create a `Plotable` object that is inserted in the channel and can be viewed using the plot viewer.

The Toolbar and Info bar GUIs for the plot viewer now have some controls for things that used to be embedded in the viewer itself--this makes more room for the plot.

### CODE REVIEW

**Comment by ejeschke** [comment]
No hurry, @pllim. This is mostly copying a little code from a plugin you wrote to a viewer you wrote.  We have a use case here.

**Comment by ejeschke** [comment]
Rebased

**Comment by pllim** [comment]
I probably won't have time till end of June. Is that too late?

**Comment by ejeschke** [comment]
Yeah, probably. Don't worry about it.

**Comment by pllim** [comment]
I might be able to review this next week if you still need help. Please let me know!

**Comment by ejeschke** [comment]
> I might be able to review this next week if you still need help. Please let me know!

No, I'm going to be adding to this, so don't worry about it for now.

**Pull request merged**
