### PR TITLE
Update astropy-helpers to v2.0.x

### PR DESCRIPTION
**Pull request by pllim**
Similar to astropy/astropy#6140. Is it too soon, @bsipocz ? I thought it's already in Astropy dev, so might as well.

(See spacetelescope/stginga#139 for `stginga`.)

### CODE REVIEW

**Comment by bsipocz** [comment]
Sure, it can be done. I've updated it in a few packages for to test the helpers itself. There will be a final helpers release just before 2.0, and after that I'll open automated PRs to update it in every affiliates.

**Comment by pllim** [comment]
Well, if Brigitta gets to that and this is still open, then we can just close this without merge.

**Comment by ejeschke** [comment]
> Well, if Brigitta gets to that and this is still open, then we can just close this without merge.

Should we hold off a bit then, in case there is a conflict with the proposed fix?

**Comment by pllim** [comment]
Sure, I'll close this.

**Pull request closed without merging**
