### PR TITLE
TST: Pin astropy in conda job

### LINKED ISSUE #946: TST: conda job pulling in old astropy
Not sure why it is not using latest released version of astropy.

`astropy-3.2.3              |   py38h516909a_0         7.2 MB  conda-forge`

As a result, I am seeing failures that are already fixed.

### PR DESCRIPTION
**Pull request by pllim**
Fix #946

### CODE REVIEW

**Comment by pllim** [comment]
Looks like a simple pin fixed the job. Perhaps it was using some cached conda thingies before...

```
astropy-4.2.1              |   py38h6323ea4_1         6.1 MB
```

**Comment by mwcraig** [comment]
This seems fine to me 😃

**Review by ejeschke — COMMENTED** [review]
Looks ok to me.  I suppose it doesn't make sense to test with `astropy` v3.x.y ?

**Comment by pllim** [comment]
LTS version of astropy is already 4.0.* and will be 5.0.* at the end of 2021, so I don't think we need to worry about astropy 3.0.* unless you have users who are locked into older versions of astropy.

**Comment by ejeschke** [comment]
I think we are using 4 in most places.

**Comment by pllim** [comment]
In that case, I'll go ahead and merge this so CI will be green again. If you still wish to test astropy 3.x in conda, we can address that in a follow-up PR. Thanks!

**Pull request merged**
