### PR TITLE
Remove imports of distutils

### LINKED ISSUE #1095: distutils is completely deprecated in python 3.12
The `distutils` module is [to be removed in python 3.12](https://docs.python.org/3.10/whatsnew/3.10.html#distutils-deprecated). 

Ginga currently imports the module in:
- `ginga.rv.plugins.MultiDim` (using `spawn()`)
- `ginga.opengl.CanvasRenderGL` (using `LooseVersion`)

### PR DESCRIPTION
**Pull request by ejeschke**
- fix #1095

for rationale, [see this](https://docs.python.org/3.10/whatsnew/3.10.html#distutils-deprecated)

This will be applied also to the 5.0.1 release.

### CODE REVIEW

**Comment by ejeschke** [comment]
@pllim, I'm not sure whether `packaging` is in the standard library or not. I suppose I might have to add it as a dependency if it is not. Still googling...

**Comment by ejeschke** [comment]
Looks like it might be not.  I'll add it to `setup.cfg`.

**Comment by ejeschke** [comment]
@pllim, I'll squash merge if you have no objection.  I've tested the changes.

**Review by pllim — APPROVED** [review]
LGTM. I think `packaging` is pretty standard now for version check. I think astropy already pulls that in for you but does not hurt to be explicit. Thanks!

**Pull request merged**
