### PR TITLE
Fixing configparser in setup

### PR DESCRIPTION
**Pull request by bsipocz**
Causing error with py 3.5.2, e.g https://travis-ci.org/astropy/conda-channel-astropy/jobs/141395583#L2108

### CODE REVIEW

**Comment by ejeschke** [comment]
Thanks, @bsipocz.  I think this same issue affected sphinx build, for which I merged a PR a few days ago.

**Comment by pllim** [comment]
Yeah, I fixed it in #352.

**Comment by bsipocz** [comment]
Yep, these import errors have started to pop up rather frequently (e.g when building the conda packages), so I used a bit of bash-fu to fix this for the packages I had locally, rather than waiting for them to switch over to the newer package-template that contains the fixes.

**Comment by ejeschke** [comment]
I think there was one in the main `setup.py`, and one for the sphinx build in `doc`.  They got fixed separately, AFAIK.

**Comment by pllim** [comment]
Oh! I thought they are the same file and was confused. Sorry for the noise.

**Pull request merged**
