### PR TITLE
RTD: Rename YAML file

### PR DESCRIPTION
**Pull request by pllim**
I think this is required for RTD to build now.

### CODE REVIEW

**Comment by pllim** [comment]
I still do not see the RTD job here. Could be the webhook is broken but I cannot see the GitHub admin settings here. On RTD site, it is getting Error 400 .

**Comment by ejeschke** [comment]
Webhook is still enabled, but is showing the error that 400 is happening on the RTD side.  

BTW, there is still a travis web hook--not using that now are we?  Should we delete it?  It's showing invalid HTTP response 503.
Also, the appveyor one is also signalling an error: invalid HTTP response 403

**Comment by pllim** [comment]
You do not need Travis CI or Appveyor CI webhooks.

You do, however, need to fix the ReadTheDocs webhook. I couldn't fix it from the RTD side. What is it saying on the GitHub side?

**Comment by ejeschke** [comment]
"Last delivery was not successful. Invalid HTTP response: 400."

**Comment by ejeschke** [comment]
Let me poke around the RTD side...

**Comment by pllim** [comment]
Is it complaining about invalid token on GH side?

**Comment by ejeschke** [comment]
Shows "passing" on RTD side.

**Comment by ejeschke** [comment]
> Is it complaining about invalid token on GH side

Not that I can see anywhere.

**Comment by ejeschke** [comment]
There is no secret in the secret box, however

**Comment by ejeschke** [comment]
No, this:
image

**Comment by pllim** [comment]
Hmm why is it not JSON?

**Comment by ejeschke** [comment]
I just kicked off a build on RTD of "latest". Double-checked that it is the correct SHA. It used the command "cat .readthedocs.yml" and successfully completed the build.  So I don't think the file extension is the issue...

**Comment by ejeschke** [comment]
Should I try switch to JSON?

**Comment by pllim** [comment]
OK closing this PR then.

> Should I try switch to JSON?

Doesn't hurt at this point. 😅

**Comment by ejeschke** [comment]
Ok, I rebased #1076 and force pushed it. Let's see what happens...

**Comment by ejeschke** [comment]
Still getting a 400 code from RTD...

**Comment by pllim** [comment]
Looks like it is still failing. There is a message on the RTD integration page for the webhook:

This integration is not managed by Read the Docs currently. If this integration is not functioning correctly, you can try re-syncing it. Otherwise you'll need to update the configuration on your repository. You can use the following address to manually configure this webhook.

To manually configure this webhook with your provider, use the following information...

**Comment by ejeschke** [comment]
Ah, there was a secret there--I have pasted this into the github side.  I'll try force pushing #1076 again.

**Comment by ejeschke** [comment]
On the RTD side, for the HTTP 400 failures, it is showing the following message:
```json
{
  "detail": "Payload not valid, invalid or missing signature"
}

**Comment by ejeschke** [comment]
Under Integrations/Exchange--can you see it?

**Comment by ejeschke** [comment]
Hmmm, thinking I might have to try the [solution here](https://stackoverflow.com/questions/64923856/readthedocs-says-could-not-add-webhook)...

**Comment by pllim** [comment]
Might as well give that a try. Good luck!

**Pull request closed without merging**
