### PR TITLE
TST: Update to setup-python v4

### LINKED ISSUE #1028: CI: pep_and_audit--`set-output` command is deprecated and will be disabled soon
We are getting the following warning in CI:
```bash
pep_and_audit
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

### PR DESCRIPTION
**Pull request by pllim**
See if it fix #1028

### CODE REVIEW

**Comment by ejeschke** [comment]
Looking good so far!

**Comment by pllim** [comment]
I think the deprecation warnings are gone in the pep_and_audit job. If you are happy with this, feel free to merge. Thanks!

**Comment by pllim** [comment]
p.s. I will let you set the milestone. 😸

**Review by ejeschke — APPROVED** [review]
LGMT, Thanks!

**Pull request merged**
