### PR TITLE
updated imexam plugin to work with imexam logging

### PR DESCRIPTION
**Pull request by sosey**
Minor updates to the original plugin to coincide with updates in the imexam module for prints and logging.

This should work with the current master and the release of 0.6.3 coming up

### CODE REVIEW

**Comment by pllim** [comment]
In regards to the workshop, this fix won't be included as per current workshop instructions nor will be in AstroConda in time. If you want participants to use this, we'll need to modify the instructions to `pip install` from master after this is merged.

**Comment by pllim** [comment]
Since you already merged the corresponding changes on `imexam` side, I don't see a reason not to merge this. And given that workshop is in 2 days, I am merging this now. I hope you're okay with this, @ejeschke .

**Comment by sosey** [comment]
I wasn't planning on demo'ing this at the workshop

**Comment by ejeschke** [comment]
No problem. Tnx!

**Pull request merged**
