### PR TITLE
Speed up LineProfile calculation etc

### LINKED ISSUE #492: Feature Request: Overplotting multiple marks on LineProfile
User wishes to overplot multiple marks on `LineProfile`.

Update: Alicia would settle for a "all or selected" option.

c/c @bhilbert4 @aliciacanipe

### LINKED ISSUE #493: LineProfile mean calculation too slow for big cube
User reported performance issues ("a few seconds") when `LineProfile` operates on a cube of dimension `[190,2048,2048]`, with "circle" region and a radius of about 30 pixels.

Under the hood, I used Numpy's `mean(axis=...)` method for masked array. Not sure how to make that faster, so I am opening an issue for now as a reminder to investigate in the future.

c/c @bhilbert4 @aliciacanipe

Alicia's timing report:

> I did a quick check on a point shape versus a circle shape.
       
>        1st point after opening Ginga: ~5 sec to get the ramp
>        Clicking on another point after that: ~1-2 sec to get the new ramp

>        1st circle after opening Ginga (r = 5 pix): ~40 sec to get the mean ramp
>
> and I get the spinning beachball
>
>        Moving the circle to another position: ~8 sec to get the mean ramp

### PR DESCRIPTION
**Pull request by pllim**
Speed up `LineProfile` calculation by getting rid of Numpy masked array overhead. Fix #493.

I thought using masked array was a elegant solution but it is not feasible for large data cube. 😢 I probably over-designed it originally... Timing info available at https://gist.github.com/pllim/d0999e1c00d4ee45ccba2585c0b8146f .

Also fix #492.

c/c @bhilbert4 @aliciacanipe

### CODE REVIEW

**Comment by pllim** [comment]
I think this is ready now. Please review.

**Comment by pllim** [comment]
c/c @nabobalis

**Comment by ejeschke** [comment]
This looks good to me, @pllim.  

I do think that the Move/Draw/Edit controls should be standardized (as much as possible) accounting for the different things that the plugins do.  And `LineProfile` is perfectly compatible in this regard, but the controls are constructed differently and show up more widely spaced than in other plugins (because they end up in a `GridBox` rather than in an `HBox`).  This is a minor point, but these types of minor inconsistencies can contribute to an overall sense of inconsistency for the application.  So I would suggest that in a future work we either make these look like the others, or make the others look like these.

**Comment by pllim** [comment]
Sure. We can open a "standardize move/draw/edit" button issue.

**Comment by ejeschke** [comment]
I'm going to go ahead and merge this then, and make a new release of ginga.  We can open up issues for fixes in the master branch for any that crop up.

**Comment by nabobalis** [comment]
Sorry, I was a bit slow!

This looks very nice.

**Comment by pllim** [comment]
Thanks!

**Comment by ejeschke** [comment]
> Sorry, I was a bit slow!

Not at all, @nabobalis!  I am just moving quickly to get a release out, since a lot of features and bug fixes have piled up in the dev line.  Thanks for your feedback!

**Pull request merged**
