### PR TITLE
Remove support for matplotlib < 2.0

### PR DESCRIPTION
**Pull request by ejeschke**
This removes support for matplotlib versions < 2.0. 

Since the "current" version of matplotlib seems to be 3.x I think this is reasonable.

### CODE REVIEW

**Comment by ejeschke** [comment]
Need to add a note to `WhatsNew`...will do so before a merge.

**Comment by ejeschke** [comment]
Good catch!

**Comment by ejeschke** [comment]
@pllim, what do you think should be the minimum version of `matplotlib` going forward?

**Comment by pllim** [comment]
astropy has `>=2.1`, so maybe we'll just copy astropy?

https://github.com/astropy/astropy/blob/679a74a463794829d1dcd02570708c21695397aa/setup.cfg#L72

**Comment by ejeschke** [comment]
> astropy has >=2.1, so maybe we'll just copy astropy?

Sounds fine.

**Comment by ejeschke** [comment]
Rebased

**Comment by ejeschke** [comment]
@pllim, ok to merge? Updated `setup.cfg` and rebased.

**Pull request merged**
