### PR TITLE
Fix zscale autocuts algorithm

### LINKED ISSUE #1041: local variable 'intercept' referenced before assignment
I see this traceback:
```
  File "ginga\ImageView.py", line 800, in _image_set_cb
    self.apply_profile_or_settings(image)
  File "ginga\ImageView.py", line 876, in apply_profile_or_settings
    self.auto_levels()
  File "ginga\ImageView.py", line 2593, in auto_levels
    loval, hival = autocuts.calc_cut_levels(image)
  File "ginga\AutoCuts.py", line 797, in calc_cut_levels
    loval, hival = self.calc_zscale(data, contrast=self.contrast,
  File "ginga\AutoCuts.py", line 830, in calc_zscale
    loval, hival = zscale.zscale_samples(samples, contrast=contrast)
  File "ginga\util\zscale.py", line 92, in zscale_samples
    ngoodpix, zstart, zslope = zsc_fit_line(samples, npix, KREJ, ngrow,
  File "ginga\util\zscale.py", line 171, in zsc_fit_line
    zstart = intercept - slope
```

As a result, cuts is set to `(0, 0)` and I have to manually adjust the cut levels for image to show properly.

My hunch is that the loop run into `break` at the very first iteration.

https://github.com/ejeschke/ginga/blob/af1756aa0fb9bda485fee2e1706836382d60547b/ginga/util/zscale.py#L128-L129

### PR DESCRIPTION
**Pull request by ejeschke**
- replaces old bundled zscale with astropy one
- fix #1041

### CODE REVIEW

**Comment by ejeschke** [comment]
@pllim, see if this has the desired fix for your data. Especially if you have a real data file, do you get acceptable estimated cuts?

**Comment by pllim** [comment]
Thanks for the quick fix! I am swamped next week but I'll review the week after. At a glance, I like the code simplification. 😸

**Review by pllim — APPROVED** [review]
The error reported in #1041 is gone. Now the same image mentioned in that issue gives a default cut level of `(0, 8)` for Slice 1 (it is a data cube). Slice 1 data range is really `[0, 89]` (inclusive).

**Comment by ejeschke** [comment]
> Slice 1 data range is really [0, 89] (inclusive).

Hmm, when I look at slice 1 of `image_cube_hdu_obj_microns.fits` (example problem image above) it looks like the min and max are approx 0.00435, 0.99.
Am I looking at the same image you are?

**Comment by pllim** [comment]
Oh ooops... I think you are right. I must have misread. I used random generator that is from 0 to 1, I think.

**Comment by pllim** [comment]
Oh wait, no, my local file must had be generated inconsistently, let me regenerate it.

**Comment by pllim** [comment]
Okay, it appears much better when the values are between 0 and 1. Cut low is 0.5007 and cut high is 0.9273.

The image I used in https://github.com/ejeschke/ginga/pull/1042#pullrequestreview-1306386829 must had been generated by a simple `np.arange` to see how the elements are arranged.

**Comment by ejeschke** [comment]
> The image I used in https://github.com/ejeschke/ginga/pull/1042#pullrequestreview-1306386829 must had been generated by a simple np.arange to see how the elements are arranged.

@pllim can you upload a problem image to the STScI box storage shared with me?  I'm inclined to merge this, but I want to be able to reliably reproduce error we are fixing and make sure that the new method is working decently to do that.

**Comment by pllim** [comment]
@ejeschke , are you able to grab https://stsci.box.com/s/xnepo5x4tbidhwub5w4t28d3o09ackfh ?

**Comment by ejeschke** [comment]
> @ejeschke , are you able to grab https://stsci.box.com/s/xnepo5x4tbidhwub5w4t28d3o09ackfh ?

Yes, thank you!

**Comment by pllim** [comment]
> Cut low is 0.5007 and cut high is 0.9273.

Without this patch, but on the latest `master` branch, cut low is 0.03439 and cut high is 0.9939. The exception reported in #1041 is no more. Thanks!

**Comment by ejeschke** [comment]
> on the latest master branch, cut low is 0.03439 and cut high is 0.9939

@pllim, with this now-modified PR, what are the cuts for the same image?

**Comment by pllim** [comment]
With this PR rebased on top of latest `master`, now I get cut low 0.03439 and cut high 0.9939, so basically this PR does not change anything except you now don't have to maintain your own zscale algorithm. 😸

**Comment by ejeschke** [comment]
Agree, but I want to check some of our images to make sure I don't see significant differences in cut values. If there are I may need to tweak this PR some more.

**Comment by ejeschke** [comment]
Seems to be some minor differences, but not enough to matter much. Merging.

**Pull request merged**
