### PR TITLE
TST: Move Windows build from Appveyor to Travis

### PR DESCRIPTION
**Pull request by pllim**
Appveyor is broken, probably by some changes in `conda` and it is not fun to fix the Powershell script over at `ci-helpers`. So it is easier to move Windows build to Travis CI, if possible.

I milestone to 3.0 because I don't think this is critical to backport, but feel free to re-milestone otherwise.

### CODE REVIEW

**Comment by ejeschke** [comment]
Travis does Windows builds now?

**Comment by pllim** [comment]
Yes, see https://docs.travis-ci.com/user/reference/windows/ . Though I heard that it does not natively supports Python but `ci-helpers` use `conda` anyway, so that should not be a problem for us, hopefully. 🤞

**Comment by ejeschke** [comment]
Woot!

**Comment by ejeschke** [comment]
Passed!

**Comment by pllim** [comment]
I'm checking the logs to be sure... Hang on. 😅

**Comment by pllim** [comment]
@ejeschke , logs seem fine to me. If you are comfortable with this switch, FFTM!

**Comment by pllim** [comment]
Ah, just saw your comment on the other PR. Okay, I'll merge this then.

**Pull request merged**
