### PR TITLE
Add Jupyter backend event handling

### PR DESCRIPTION
**Pull request by ejeschke**
This PR is conditional on [this PR](https://github.com/jupyter-widgets/ipywidgets/pull/1727) getting merged in the `ipywidgets` package.  It adds full support for all important UI events for a complete ginga viewer widget running in a Jupyter notebook.

### CODE REVIEW

**Comment by ejeschke** [comment]
ping @mwcraig

**Comment by mwcraig** [comment]
It'll be a couple days but looking forward to trying this out!

**Comment by ejeschke** [comment]
Rebased

**Comment by ejeschke** [comment]
Rebased.

**Comment by ejeschke** [comment]
Rebased and modified to use new `ipyevents` module.

**Comment by ejeschke** [comment]
@mwcraig, can you try this and make sure it is working as expected?

I am noticing something new--a kind of flickering when objects are drawn on the image.  I did not see that previously.  But I am testing now with a `pip` install of the requirements, instead of git checkouts.

**Comment by ejeschke** [comment]
One thing we still need to address is getting a python callback when the Image widget (ipywidget) is resized.  That is really the last thing we need.  Don't know if that is possible through the regular ipywidgets package.

**Comment by ejeschke** [comment]
@mwcraig, I had a couple of late fixes to this PR.  You'll notice that scrolling now controls panning, rather than zoom, by default.  I'm trying to be more consistent between backends.  Qt5 can discriminate between a mouse wheel and a trackpad, and I've set that up so that track pad events are mapped to a pan callback.  I think it is much friendlier to laptop users.  With web widgets it is a bit more difficult, so I'm thinking the default should be pan.  Try using +/- keys to zoom (they do not need to be shifted).  Let me know how you feel about this.  You can customize it completely, of course, with some boilerplate code to set up the viewer--but I'm trying to make sensible defaults.

**Comment by ejeschke** [comment]
I'd like to add this to a new Ginga release this week, so LMK ASAP. Tnx!

**Comment by ejeschke** [comment]
> This PR is conditional on this PR getting merged in the ipywidgets package.

Just a note that this is no longer a requirement, as the required functionality is released as a standalone package [ipyevents](https://github.com/mwcraig/ipyevents)

**Comment by mwcraig** [comment]
Will have comments to you later today!

**Comment by mwcraig** [comment]
@ejeschke -- I tried this out and it works great. I showed the new interface to a few students I'm traveling with (including one who had tried the old setup on a trackpad) and they all liked the scroll-to-pan/keys-to-zoom setup.

I imagine refining it more down the road, but think a release soon that contains this functionality would already be a big step forward.

**Comment by ejeschke** [comment]
Did you see any flickering when you did drawing?

**Comment by mwcraig** [comment]
No, it was actually much smoother than the older version. With the other one I often had flickering while panning, with this one, though, no problem. Haven’t tested it real extensively, to be fair....

**Comment by mwcraig** [comment]
Also, about to 🛫, not sure if I’ll be available in-flight, but back online in 2-2.5 hours.

**Comment by ejeschke** [comment]
Super.  Ok, going to merge b/c I'd like to get this in the next release.  We can improve upon it down the road.

**Pull request merged**
