### PR TITLE
Update astropy-helpers to v1.3

### PR DESCRIPTION
**Pull request by bsipocz**
This is an automated update of the astropy-helpers submodule to v1.3. This includes both the update of the astropy-helpers sub-module, and the ``ah_bootstrap.py`` file, if needed.

*This is intended to be helpful, but if you would prefer to manage these updates yourself, or if you notice any issues with this automated update, please let @astrofrog know!*

### CODE REVIEW

**Comment by pllim** [comment]
LGTM :+1:

**Comment by ejeschke** [comment]
@pllim, you did the work to merge the `astropy-helpers`.  Are there any issues with conda or "typical" installs? I assume that if this version is in PyPI then there should be no major problems?

**Comment by bsipocz** [comment]
@ejeschke - The changes between v1.2 and v1.3 of the helpers is quite minimal and mostly about dealing with upstream deprecations. The only significant change is that we renamed  ``build_sphinx`` to ``build_docs``, but the former still works.

**Comment by pllim** [comment]
@ejeschke , as @bsipocz mentioned, this update should not impact Ginga. The tests passed, so that is a good sign as well.

**Comment by ejeschke** [comment]
Ok, good to hear. Merging.

**Pull request merged**
