### PR TITLE
DOC: Jupyter slider demo

### PR DESCRIPTION
**Pull request by pllim**
Add a new demo notebook on how to implement a simple slider for multi-extension FITS image.

A semi-rendered notebook can be viewed at https://gist.github.com/pllim/f0d465eaf4eb45f9bcd2cccd1779dea3 (except the widgets, which will only show properly when you run it locally).

### CODE REVIEW

**Comment by ejeschke** [comment]
I'm asking because I had some trouble running this backend recently and wondering whether it is just my setup.

**Comment by pllim** [comment]
Here are my version info:
```
ipywidgets                7.0.0            py36h7b55c3a_0
ipyevents                 0.3.0                    py36_0    conda-forge
pyqt                      5.6.0            py36h0386399_5
qt                        5.6.2               h974d657_12
qtconsole                 4.3.1            py36h8f73b5b_0
qtpy                      1.3.1            py36h3691cc8_0
```
Python 3.6.5 on RHEL7 64-bit.

**Comment by pllim** [comment]
@ejeschke , by the way, I didn't try using key binding or any fancy shortcuts. My focus was simply on the slider, which works.

**Comment by pllim** [comment]
@ejeschke I also can modify this notebook to use the slider on top of `ginga_ipython_demo.ipynb` if you are more comfortable with that. Just let me know!

**Comment by ejeschke** [comment]
> I also can modify this notebook to use the slider on top of `ginga_ipython_demo.ipynb` if you are more comfortable with that.

No need.  But maybe if we develop this notebook to showcase the widget more we can remove the other one.  Feel free to merge, @pllim!

**Pull request merged**
