### PR TITLE
Add convenience functions for working with astropy NDData objects

### PR DESCRIPTION
**Pull request by ejeschke**
This PR adds convenience functions for working with astropy `NDData` objects.  Specifically, it adds support to the `AstroImage` class for loading `NDData` (or `NDData`-subclassed) objects and making an `NDData` object from an `AstroImage` object.  The conversions preserve data, header and wcs.

Examples:
```python
img = AstroImage()
img.load_nddata(ndd)

ndd2 = img.as_nddata()
ndd3 = img.astype('nddata')
```
this PR also adds support for converting to a `PrimaryHDU` object:
```python
hdu1 = img.as_hdu()
hdu2 = img.astype('hdu')
```

### CODE REVIEW

**Comment by ejeschke** [comment]
Ping @pllim.  Do you work much with `NDData` or `CCDData` objects?

Wondering if the method `load_nddata()` should also handle the `inherit_primary_header` business, or whether that can be confined to dealing with FITS HDUs?

**Comment by ejeschke** [comment]
Strange travis failure in building documentation.

**Comment by pllim** [comment]
Re: failure -- That is because you have warnings in your Sphinx build. Looks like some missing reference in API doc:
```
/home/travis/build/ejeschke/ginga/doc/ref_api.rst:141: WARNING: toctree references unknown document 'api/ginga.util.wcsmod.my_import'
```

**Comment by pllim** [comment]
You might need to be very explicit in selecting which API doc to render via Sphinx in `wcsmod/__init__.py`, as `from ginga.misc.ModuleManager import my_import` is what gave the warning. Currently, the following in `ref_api.rst` is no longer sufficient:
```rst
.. automodapi:: ginga.util.wcsmod
   :skip: use
   :skip: get_wcs_wrappers
```

**Comment by pllim** [comment]
>  Do you work much with NDData or CCDData objects?

@ejeschke , unfortunately I don't. @mwcraig or @Cadair might have more input on this than me.

**Comment by ejeschke** [comment]
Rebased.

**Comment by ejeschke** [comment]
Added unit tests.

**Comment by ejeschke** [comment]
@pllim, unless you have any objections I'm going to go ahead and merge this.

**Pull request merged**
