### PR TITLE
MNT: Ignore import error in pytest collection

### PR DESCRIPTION
**Pull request by pllim**
This is an automated update made by the `batchpr` tool :robot: to future-proof test collection behavior `pytest-doctestplus` - feel free to close if it doesn't look good or isn't relevant! You can report issues to @pllim.

### CODE REVIEW

**Comment by ejeschke** [comment]
@pllim, deferring to you on this one...

**Comment by pllim** [comment]
Well, I am obviously biased since I submitted the PR. Do you use `doctest`? Do you use or plan to use `pytest-doctestplus`? If yes to either or both, you probably want this. If not, then you don't need it.

**Comment by ejeschke** [comment]
I have not used `doctest`, but if that is something that runs tests embedded in documentation, it sounds useful.

**Comment by pllim** [comment]
In that case, should we close this without merge? Seems like it won't be used for now anyway?

**Comment by ejeschke** [comment]
Unless you think it would cause problems, I think we should merge it.  I could see writing some doctests in the future. I haven't before, mostly because I wasn't really aware of the tooling.

**Comment by pllim** [comment]
Okay, merging then. You can always take it back out if you don't like it. I cannot find any good documentation for this option. But you can see https://docs.pytest.org/en/latest/_modules/_pytest/doctest.html .

`doctest` is good for non-GUI code examples. I don't think it is meant for GUI testing. FYI.

**Pull request merged**
