### PR TITLE
Do more sophisticated parsing of config files

### LINKED ISSUE #859: Is there a way to have multi-line config value for plugin?
In [DQInspect](https://stginga.readthedocs.io/en/stable/stginga/plugins_manual/dqinspect.html), I found myself writing a very long config item in `~/.ginga/plugin_DQInspect.cfg`:
```python
dqdict = {'NIRCAM': 'data/dqflags_jwst.txt', 'NIRSPEC': 'data/dqflags_jwst.txt', ..., 'WFPC2': 'data/dqflags_hstgen.txt'}
```

I wonder if there is a way to add in line breaks so it is more human-readable in a way that won't break Ginga.
```python
dqdict = {'NIRCAM': 'data/dqflags_jwst.txt',
          'NIRSPEC': 'data/dqflags_jwst.txt',
          ...,
          'WFPC2': 'data/dqflags_hstgen.txt'}
```

It is okay if that is not possible. I am just wondering. Thanks!

### PR DESCRIPTION
**Pull request by ejeschke**
- now allows line breaks in values, for more readable configs
- (fix #859)

### CODE REVIEW

**Comment by ejeschke** [comment]
@pllim, this may do the trick, but it needs testing. Recommend no merge until after 3.1 release.

**Comment by pllim** [comment]
For reference, this is my current `~/.ginga/general.cfg`. Towards the bottom are some settings that are for `stginga` if they look foreign to you.

```
#
# General preferences for Ginga
#
# Place this in file under ~/.ginga with the name "general.cfg"

# Import matplotlib colormaps in addition to our own set if matplotlib
# is installed
useMatplotlibColormaps = True

# Show startup banner (automatically set after first run)
showBanner = False

# Number of images to keep in memory per channel (0 = unlimited)
numImages = 0

# Force a widget set
# Possibilities are 'choose', 'gtk2', 'qt4', 'qt5' or 'pyside'
widgetSet = 'choose'

# Force of package for handling WCS
# Possibilities are 'choose', 'kapteyn', 'astlib', 'starlink' and 'astropy'
#WCSpkg = 'choose'
#WCSpkg = 'astlib'
#WCSpkg = 'kapteyn'
#WCSpkg = 'starlink'
WCSpkg = 'astropy'
#WCSpkg = 'astropy2'
#WCSpkg = 'barebones'

# Choice of package for handling FITS I/O
# Possibilities are 'choose', 'astropy' and 'fitsio'
#FITSpkg = 'choose'
FITSpkg = 'astropy'
#FITSpkg = 'fitsio'

# Set python recursion limit
# NOTE: Python's default of 1000 causes problems for the standard logging
# package that Ginga uses in certain situations.  Best to increase it a bit.
recursion_limit = 3000

# Pixel coordinates offset
pixel_coords_offset = 1.0

# Inherit PRIMARY (EXT=0) header for multi-extension FITS
inherit_primary_header = True

# Header keywords. These can be in PRIMARY header only if it is inherited.
extnamekey = 'EXTNAME'
extverkey = 'EXTVER'
sciextname = 'SCI'
errextname = 'ERR'
#errextname = 'ERROR'
dqextname = 'DQ'
instrumentkey = 'INSTRUME'
targnamekey = 'TARGNAME'
```

**Comment by pllim** [comment]
It is choking at `showBanner` and `numImages`.

```python
>>> from ginga.misc.Settings import strip_comments, make_assignments
>>> buf2 = list(strip_comments(buf.split('\n')))
>>> buf2
[(7, 'useMatplotlibColormaps = True'),
 (10, 'showBanner = False'),
 (13, 'numImages = 0'),
 (17, "widgetSet = 'choose'"),
 (25, "WCSpkg = 'astropy'"),
 (32, "FITSpkg = 'astropy'"),
 (38, 'recursion_limit = 3000'),
 (41, 'pixel_coords_offset = 1.0'),
 (44, 'inherit_primary_header = True'),
 (47, "extnamekey = 'EXTNAME'"),
 (48, "extverkey = 'EXTVER'"),
 (49, "sciextname = 'SCI'"),
 (50, "errextname = 'ERR'"),
 (52, "dqextname = 'DQ'"),
 (53, "instrumentkey = 'INSTRUME'"),
 (54, "targnamekey = 'TARGNAME'")]
>>> buf3 = list(make_assignments(buf2))
>>> buf3
[(7, 'useMatplotlibColormaps', 'True'),
 (10, 'showBanner', 'False numImages = 0'),  # <--- Wrong
 (17, 'widgetSet', "'choose'"),
 (25, 'WCSpkg', "'astropy'"),
 (32, 'FITSpkg', "'astropy'"),
 (38, 'recursion_limit', '3000'),
 (41, 'pixel_coords_offset', '1.0'),
 (44, 'inherit_primary_header', 'True'),
 (47, 'extnamekey', "'EXTNAME'"),
 (48, 'extverkey', "'EXTVER'"),
 (49, 'sciextname', "'SCI'"),
 (50, 'errextname', "'ERR'"),
 (52, 'dqextname', "'DQ'"),
 (53, 'instrumentkey', "'INSTRUME'")]
```

**Comment by ejeschke** [comment]
Fixed the regex.  Can you try again?

**Comment by ejeschke** [comment]
If you write a new config file (or save one) and then try to run an older version of Ginga it will fail to read the new config file.  Just something to consider when we get around to this PR again later.

**Comment by pllim** [comment]
Yes, I am pondering that over at spacetelescope/stginga#193 . I don't think it is a problem although user education is necessary.

**Comment by pllim** [comment]
3.1 is out, so merging. Thanks!

**Pull request merged**
