### PR TITLE
Add splitter to PlotTable plugin, similar to other plugins with plots

### PR DESCRIPTION
**Pull request by ejeschke**
This adds a splitter to the PlotTable plugin, so that the user can adjust the height of the plot (they can already adjust the width). This is similar to what the other plotting plugins do.

### CODE REVIEW

**Comment by ejeschke** [comment]
@pllim, when you have time.  Not urgent.

**Comment by ejeschke** [comment]
Good point!  Do you want to make it with the FITS data that was used to make the existing plot? I think you can just push a commit to this PR.  If not I will make a plot with new data.

**Comment by pllim** [comment]
@ejeschke , feel free to update the plot with your own data. I think I just used a Vega spectrum and zoom into one of the absorption lines; nothing too fancy.

**Comment by ejeschke** [comment]
@pllim, I updated the screen shot.  Let me know what you think.  We don't deal with too many tables here so I don't have a lot of examples available.

**Comment by pllim** [comment]
In that case, I can submit an alternate screenshot, but can't do it today. 🤔

**Comment by ejeschke** [comment]
No worries.  Take a look at the example I submitted.  I think your data looks more interesting, but I'm ok with either.  I included the channel viewer in the screenshot (here, a `TableViewer`) showing the columns plotted.  I think that is more in line with what we have been doing with the screenshots lately.

**Comment by pllim** [comment]
@ejeschke , if I push directly to this PR, I would need to squash your image out. Would you mind?

**Comment by ejeschke** [comment]
Thanks!

**Pull request merged**
