### PR TITLE
Added directory browser widget

### PR DESCRIPTION
**Pull request by pllim**
Added directory browser widget (GTK and Qt). I need this for spacetelescope/stginga#87 but it is just generally useful for Ginga to have anyway.

Disclaimer: Untested under GTK but theoretically should work if http://stackoverflow.com/questions/10868167/make-filechooserdialog-allow-user-to-select-a-folder-directory answer is correct.

### CODE REVIEW

**Comment by ejeschke** [comment]
@pllim, are these similar enough to the existing `FileSelection` objects that the latter could just take a keyword argument to make them select folders only?

**Comment by pllim** [comment]
@ejeschke , for Qt widget, `FileSelection` is a bit more complicated (wildcard etc.), so subclassing is not feasible.

**Comment by pllim** [comment]
See #239 for related `FileSelection` PR that was merged.

**Comment by ejeschke** [comment]
Ok, cool.

**Comment by pllim** [comment]
Thanks!

**Pull request merged**
