### PR TITLE
Added data directory

### PR DESCRIPTION
**Pull request by pllim**
Added data directory and updated setup script. This is in response to a request in #166.

This directory will be used for Ginga data files, which can be accessed via Astropy as follows. The example below uses a custom local plugin but data file may belong to any sub-module within Ginga, as desired:
```python
from astropy.io import ascii
from astropy.utils.data import get_pkg_data_filename

from ginga import GingaPlugin


class MyLocalPlugin2(GingaPlugin.LocalPlugin):
    def __init__(self, fv, fitsimage):
        super(MyLocalPlugin2, self).__init__(fv, fitsimage)

        # Load associated data file in ginga/data
        # In this example, it is a plain ASCII table.
        # The "package" keyword is optional? I needed it for shared namespace but
        # unsure if it is part of the core distribution.
        datafile = get_pkg_data_filename('data/mylocalplugin2_table.txt', package='ginga')
        self.tab = ascii.read(datafile, ...)       
```

### CODE REVIEW

**Comment by pllim** [comment]
@eteq, you might also be interested in this as you consider the alternate `stginga` packaging idea.

**Comment by ejeschke** [comment]
@pllim, what is the status of this PR?  Did you resolve the issues with finding the data directory or do you want to pursue alternate implementation?  Just going through some remaining PRs now.

**Comment by pllim** [comment]
This just adds a placeholder directory for your package data, as you requested. I do not really need this for my own package data in the shared namespace. Looking up my own package data is resolved by #183.

**Comment by pllim** [comment]
If #183 is "no go", I think we can close this as well without merging.

**Comment by ejeschke** [comment]
Sounds good.  I'll be interested to hear how your method works out.  I like the idea of plugins registering themselves somehow on the install so that there is no need for autodiscovery.

Are you using the shared namespace feature still?

**Comment by pllim** [comment]
No, @eteq changed the structure such that it is contained within `stginga` itself. So our "discovery" uses the existing custom plugin architecture.

**Comment by pllim** [comment]
I opened #207 for pursuing "registering".

**Pull request closed without merging**
