### PR TITLE
TST: Stop ignoring warnings

### PR DESCRIPTION
**Pull request by pllim**
I was wondering how #930 fell through the cracks and then I noticed that we have been ignoring warnings in `pytest`.

~I suspect this will smoke out a lot of warnings, so I still put this on draft status for now until we can figure out how to handle them.~

Well, that was easier than expected. This is ready for review now.

### CODE REVIEW

**Comment by pllim** [comment]
Huh... Interesting, no other warning other than numpy size (which seems harmless). Maybe we don't test the stuff affected in #930 here in the CI. 🤷

**Comment by ejeschke** [comment]
Is it giving a deprecation warning?

**Comment by pllim** [comment]
@ejeschke , for #930 , yes.

**Review by ejeschke — APPROVED** [review]
Looks ok to me, @pllim. 

Just out of curiosity, do you have any insight as to the two warnings we are filtering (size changed)?

**Comment by pllim** [comment]
I think it is from upstream. For example, this one is from `astropy` and it is a known issue -- https://github.com/ejeschke/ginga/runs/1936579281?check_suite_focus=true

**Comment by pllim** [comment]
If you are okay with this, please merge. Thanks!

**Comment by ejeschke** [comment]
> If you are okay with this, please merge. Thanks!

@pllim, ok to squash and merge, or do you want to retain commits?

**Comment by pllim** [comment]
Feel free to squash! 😸

**Pull request merged**
