### PR TITLE
WIP: add Undistort plugin -- roughly correct for SIP distortion

### PR DESCRIPTION
**Pull request by ejeschke**
Adds a plugin called "Undistort".

It does a quick image correction for distortion information contained in the SIP WCS.

Load an image that is distorted.  Open Utils->Undistort.  Click the "Undistort" button to quickly correct for distortion.

NOTE: in this implementation, `NaN`s are substituted for pixels that are not mapped in the distortion-corrected image.

### CODE REVIEW

**Comment by ejeschke** [comment]
@pllim, is this more what you had in mind, rather than #813?

**Comment by ejeschke** [comment]
If #813 seems promising we can close this one.  Let's leave it open until we decide about it. Priority for evaluation should be #813 first.

**Comment by ejeschke** [comment]
> Should we close this in favor of #813 ?

@pllim, I vote in favor of closing this PR.

**Comment by ejeschke** [comment]
Unmerged.

**Comment by pllim** [comment]
Okay. Thanks!

**Pull request closed without merging**
