### PR TITLE
Fix test failures on v2.x

### LINKED ISSUE #765: TST: Appveyor failed
https://ci.appveyor.com/project/pllim/ginga/builds/23759091 for the latest commit to `master`.

### PR DESCRIPTION
**Pull request by pllim**
Fix #765 

TODO:

- [ ] Check to see if Travis passed
- [ ] Check to see if Appveyor passed

### CODE REVIEW

**Comment by pllim** [comment]
@ejeschke , Appveyor is not starting for pull request. Did you let its webhook take PR push events? I can't see the repo settings to check.

**Comment by ejeschke** [comment]
I think it was just set to trigger on pushes.  I've updated it to fire on PRs as well.

**Comment by ejeschke** [comment]
@pllim, I restarted the Travis build.  What do we need to do to get the appveyor build to pass?

**Comment by pllim** [comment]
There is a chance that Appveyor stopped supporting PY2 and we simply can't do it anymore. I wasn't able to figure it out in an hour and unfortunately, this is not high on my priority list right now.

**Comment by ejeschke** [comment]
No worries. I think this is low priority.

**Comment by pllim** [comment]
@ejeschke , is this still relevant? I am thinking to just abandon the CI of the 2.x releases.

**Comment by ejeschke** [comment]
> I am thinking to just abandon the CI of the 2.x releases

I think that is reasonable.  If we add any commits we can just confirm by running the test suite locally.

**Pull request closed without merging**
