### PR TITLE
Correct WebKit package name for gtk3

### PR DESCRIPTION
**Pull request by chyan26**
The WebKit package is renamed as "WebKit2".  The correction fixes the gtk3 backend display.

### CODE REVIEW

**Comment by pllim** [comment]
Hi. This change does not seem backward compatible. However, is backward compatibility required here? I can't say because I don't use this backend.

**Comment by ejeschke** [comment]
@pllim, wait a little.  I've advised him and he will be submitting a backward-compatible version.  I expect it will be pushed up soon.

**Comment by ejeschke** [comment]
@chyan26 , can you remove the commented out "pass" and "import gi" statements? Thanks.

**Comment by chyan26** [comment]
Thanks the help from @ejeschke  and comment from @pllim.  I have made the changes.

**Comment by ejeschke** [comment]
@chyan26, I tested compatibility with Gtk 3 and it works.  However, your PR is failing the PEP-8 test in Travis CI on line 32, because the comment "#noqa" should be "# noqa" (i.e. need a space after the comment character).  Can you fix it? Tnx

**Pull request merged**
