### PR TITLE
MNT: Downgrade layout warning to info

### PR DESCRIPTION
**Pull request by pllim**
Direct follow up of #763 . Same thought process as #860.

### CODE REVIEW

**Comment by pllim** [comment]
Does assigning it to me means you are okay with this? 😹

**Comment by ejeschke** [comment]
> Does assigning it to me means you are okay with this?

@pllim, I don't really know what that assign business is good for with this particular project, but I just figure "your" PRs are yours and "my" PRs are mine and "our" PR are "ours". :smile:

**Comment by ejeschke** [comment]
Are you seeing the warning over and over after deleting your layout files and letting Ginga regenerate them?

**Comment by pllim** [comment]
> This warning shouldn't normally be issued

I only see it when I manually delete the file in my `~/.ginga` to get a fresh copy. I feel like it shouldn't be a warning because it is a no-op for a user. If you disagree, we can close this without merging.

**Comment by ejeschke** [comment]
@pllim, see #866 as an alternate that avoid issuing a warning if the file does not exist.

**Pull request closed without merging**
