### PR TITLE
Fix readthedocs build due to sphinx incompatibility with RTD theme

### LINKED ISSUE #1062: RTD has error
Whatever you just pushed to `main` branch broke RTD. FYI.

https://readthedocs.org/projects/ginga/builds/21551221/

### PR DESCRIPTION
**Pull request by ejeschke**
- fix #1062

### CODE REVIEW

**Comment by ejeschke** [comment]
A bit hacky, but I guess we can revert it once sphinx 7.x supports the RTD theme. LMK what you think @pllim

**Comment by pllim** [comment]
This seems a little excessive. Why not pin it here?

https://github.com/ejeschke/ginga/blob/cf221462286cc8f9003975cfd0bccf57d8e16acc/setup.cfg#L67

**Comment by ejeschke** [comment]
> This seems a little excessive. Why not pin it here?
> 
> https://github.com/ejeschke/ginga/blob/cf221462286cc8f9003975cfd0bccf57d8e16acc/setup.cfg#L67

If that works, I'm all for it!  Can I say:
```python
docs = sphinx<7.0, sphinx-astropy; sphinx_rtd_theme
```
?

**Comment by ejeschke** [comment]
It works! LGTM, @pllim?

**Comment by ejeschke** [comment]
I will squash out the previous commits.

**Review by pllim — APPROVED** [review]
LGTM, FFTM. Thanks!

You can use the Squash and Merge button if you want.

**Comment by ejeschke** [comment]
Thanks, @pllim!

**Pull request merged**
