### PR TITLE
PEP8 check is no longer allowed failure

### LINKED ISSUE #563: Remove "allowed failure" status on PEP8 test on Travis
Currently there are about 2700 warnings from `flake8` check on Travis CI. They are simple to fix, despite tedious. Once they are fixed, we can remove the "allowed failure" status of PEP8 check in `.travis.yml`. To make review less painful, this can even be broken into multiple small PRs, addressing one sub-section at a time.

To avoid conflict, this should wait until #548 is merged.

### PR DESCRIPTION
**Pull request by pllim**
This is #585 (and #588) that includes also #565, #566, #567, #568, #569, #570, #571, #573, #574, #575, #576, #577, #578, #579, #580, #581, #582, #583, and #584.

Fix #563

### CODE REVIEW

**Comment by pllim** [comment]
GitHub, "We continue to investigate a large queue backlog. Commits will take longer than usual to appear in pull requests."

So, that must be why my commits did not appear. Sorry for so many duplicate PRs. I guess I'll just wait this one out...

**Comment by pllim** [comment]
PEP8 check passed! 🎉  I will install this locally and test it a bit when I get the chance. In the meantime, feel free to take this for a spin as well and report any issues here. Thank you.

**Comment by ejeschke** [comment]
Thanks for redoing it this way, @pllim.  I think it will be much easier to test.

**Comment by ejeschke** [comment]
I get the following traceback when starting up:
```python
Traceback (most recent call last):
  File "/home/eric/bin/myginga3", line 14, in <module>
    main.reference_viewer(sys.argv)
  File "/home/eric/Git/Ginga/ginga/rv/main.py", line 669, in reference_viewer
    viewer.main(options, args)
  File "/home/eric/Git/Ginga/ginga/rv/main.py", line 552, in main
    ginga_shell.add_channel(chname)
  File "/home/eric/Git/Ginga/ginga/rv/Control.py", line 1161, in add_channel
    workspace=workspace)
  File "/home/eric/Git/Ginga/ginga/rv/Control.py", line 1662, in add_viewer
    fi = self.build_viewpane(settings, size=size)
  File "/home/eric/Git/Ginga/ginga/rv/Control.py", line 1615, in build_viewpane
    bclass = Viewers.ImageViewCanvas.bindingsClass
AttributeError: module 'ginga.gw.Viewers' has no attribute 'ImageViewCanvas'
```

**Comment by pllim** [comment]
Yes, I can indeed re-produce that. Sorry, I'll fix it up.

**Comment by pllim** [comment]
I think I found the problem. I accidentally deleted an import because PEP8 was complaining the import was not used. I'll fix it tomorrow. Sorry!

**Comment by ejeschke** [comment]
> I accidentally deleted an import because PEP8 was complaining the import was not used. I'll fix it tomorrow.

Sounds good.  Yes, some of the imports are used to force things into the module namespace.  I think I marked some of these with a comment, but probably not all.

**Comment by pllim** [comment]
@ejeschke , I fixed the error. Still testing (a lot of things to test) but so far, I haven't encountered anymore errors. Please give this a try again. Thanks!

**Comment by ejeschke** [comment]
Now starting up ok.  I'll give it a good workout and report back.

**Comment by ejeschke** [comment]
@pllim, haven't tested exhaustively, but checks across a few backends seem to indicate nothing broken.

**Comment by pllim** [comment]
@ejeschke , I have been testing under Python 3.6 myself and should have a conclusion later today. Did you test it in Python 2 as well?

**Comment by ejeschke** [comment]
> Did you test it in Python 2 as well?

No, not yet.

**Comment by pllim** [comment]
I have not found any issues related to this PR yet in Python 3.6. I did find other issues that seem unrelated and opened new issues for them, as you might have noticed. I don't support Ginga in Python 2 for my work, so I have little motivation to re-test this under Python 2 (as it is quite time consuming). If you are okay with the changes here, feel free to merge. Thank you!

**Comment by ejeschke** [comment]
I gave it a pretty good workout with the plugins we rely on with Python 2.  Looks good.  Merging.

**Comment by pllim** [comment]
Thanks! 😄

**Comment by ejeschke** [comment]
Getting a [travis CI failure](https://travis-ci.org/ejeschke/ginga/jobs/292742752).  @pllim, can you take a look?

**Comment by pllim** [comment]
Huh, now it is complaining about all the `l` variables. Maybe `flake8` has just added that, which I didn't catch with my PR. Do you want me to fix these, or just add that to white-list?

**Comment by ejeschke** [comment]
I think we'd better whitelist those.  Is that because in some fonts they resemble a "1"?  Not a very good reason to complain, IMO.

**Comment by pllim** [comment]
`flake8` has a history of adding/removing complains, so 👍 to white-list. See #605

**Comment by ejeschke** [comment]
Ok, the current errors seem to be for new commits.  I'll have to start running flake8 to vet my commits--probably a good idea.  I'll merge this and then fix the other errors.

**Pull request merged**
